ALTER TABLE [LOCATION_STATUS_TYPES]
ADD [COLOR_CODE] nvarchar(6)  NULL 

ALTER TABLE [LOCATION_STATUS_TYPES]
ADD [BLINKING] bit NULL


USE [BHSDB]
GO
INSERT [dbo].[LOCATION_STATUS_TYPES] ([TYPE], [DESCRIPTION], [COLOR_CODE], [BLINKING]) VALUES (N'01', N'Bag Jam', N'FFA500', 1)
INSERT [dbo].[LOCATION_STATUS_TYPES] ([TYPE], [DESCRIPTION], [COLOR_CODE], [BLINKING]) VALUES (N'02', N'Inverter fault', N'0404B4', 1)
INSERT [dbo].[LOCATION_STATUS_TYPES] ([TYPE], [DESCRIPTION], [COLOR_CODE], [BLINKING]) VALUES (N'03', N'Running', N'00FF00', 0)
INSERT [dbo].[LOCATION_STATUS_TYPES] ([TYPE], [DESCRIPTION], [COLOR_CODE], [BLINKING]) VALUES (N'04', N'Ready', N'00FFFF', 0)
INSERT [dbo].[LOCATION_STATUS_TYPES] ([TYPE], [DESCRIPTION], [COLOR_CODE], [BLINKING]) VALUES (N'05', N'Die Back', N'FFFF00', 1)
INSERT [dbo].[LOCATION_STATUS_TYPES] ([TYPE], [DESCRIPTION], [COLOR_CODE], [BLINKING]) VALUES (N'06', N'Isolator Off', N'808080', 1)