USE [BHSDB]
GO

/****** Object:  Table [dbo].[LOCATION_STATUS_TYPES]    Script Date: 24-Mar-14 2:47:19 PM ******/
DROP TABLE [dbo].[LOCATION_STATUS_TYPES]
GO

/****** Object:  Table [dbo].[LOCATION_STATUS_TYPES]    Script Date: 24-Mar-14 2:47:19 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[LOCATION_STATUS_TYPES](
	[TYPE] [varchar](2) NOT NULL,
	[DESCRIPTION] [nvarchar](50) NOT NULL,
	[COLOR_CODE] [varchar](6) NULL,
	[BLINKING] [bit] NULL,
 CONSTRAINT [PK_LOCATION_STATUS_TYPES] PRIMARY KEY CLUSTERED 
(
	[TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


USE [BHSDB]
GO
INSERT [dbo].[LOCATION_STATUS_TYPES] ([TYPE], [DESCRIPTION], [COLOR_CODE], [BLINKING]) VALUES (N'01', N'Bag Jam', N'FFA500', 1)
INSERT [dbo].[LOCATION_STATUS_TYPES] ([TYPE], [DESCRIPTION], [COLOR_CODE], [BLINKING]) VALUES (N'02', N'Inverter fault', N'0404B4', 1)
INSERT [dbo].[LOCATION_STATUS_TYPES] ([TYPE], [DESCRIPTION], [COLOR_CODE], [BLINKING]) VALUES (N'03', N'Running', N'00FF00', 0)
INSERT [dbo].[LOCATION_STATUS_TYPES] ([TYPE], [DESCRIPTION], [COLOR_CODE], [BLINKING]) VALUES (N'04', N'Ready', N'00FFFF', 0)
INSERT [dbo].[LOCATION_STATUS_TYPES] ([TYPE], [DESCRIPTION], [COLOR_CODE], [BLINKING]) VALUES (N'05', N'Die Back', N'FFFF00', 1)
INSERT [dbo].[LOCATION_STATUS_TYPES] ([TYPE], [DESCRIPTION], [COLOR_CODE], [BLINKING]) VALUES (N'06', N'Isolator Off', N'808080', 1)
