USE [BHSDB_OKC]
GO

/****** Object:  UserDefinedTableType [dbo].[FLIGHT_PLAN_ALLOC_TABLETYPE]    Script Date: 02-04-2014 11:23:39 AM ******/
CREATE TYPE [dbo].[FLIGHT_PLAN_SORTING_TABLETYPE] AS TABLE(
	[TIME_STAMP] [datetime] NOT NULL,
	[DATA_ID] [bigint] NULL,
	[AIRLINE] [varchar](3) NOT NULL,
	[FLIGHT_NUMBER] [varchar](5) NOT NULL,
	[FLIGHT_NUMBER_SUFFIX] [varchar](3) NULL,
	[HANDLER] [varchar](20) NULL,
	[SDO] [datetime] NOT NULL,
	[STO] [varchar](4) NULL,
	[EDO] [datetime] NULL,
	[ETO] [varchar](4) NULL,
	[ADO] [datetime] NULL,
	[ATO] [varchar](4) NULL,
	[IDO] [datetime] NULL,
	[ITO] [varchar](4) NULL,
	[BLOCK_OFF_TIME] [varchar](14) NULL,
	[FINAL_DEST] [varchar](3) NULL,
	[DEST1] [varchar](3) NULL,
	[DEST2] [varchar](3) NULL,
	[DEST3] [varchar](3) NULL,
	[DEST4] [varchar](3) NULL,
	[DEST5] [varchar](3) NULL,
	[CANCELLED] [varchar](1) NULL,
	[AIRCRAFT_TYPE] [varchar](4) NULL,
	[HANDLER_SPECIFIC_DESC] [varchar](12) NULL,
	[AIRCRAFT_VERSION] [varchar](12) NULL,
	[TERMINAL] [varchar](5) NULL,
	[CHECKIN_AREA] [varchar](10) NULL,
	[CHECKIN_STATUS] [varchar](10) NULL,
	[PUBLIC_REMARK_CODE] [varchar](10) NULL,
	[PIER] [varchar](5) NULL,
	[GATE] [varchar](5) NULL,
	[PARKING_STAND] [varchar](5) NULL,
	[NATURE] [varchar](15) NULL,
	[SORTING_DEST1] [varchar](10) NULL,
	[SORTING_DEST2] [varchar](10) NULL,
	[GENERAL_PURPOSE] [varchar](40) NULL,
	[FI_EXCEPTION] [varchar](10) NULL,
	[MASTER_AIRLINE] [varchar](3) NULL,
	[MASTER_FLIGHT_NUMBER] [varchar](5) NULL,
	[MASTER_FLIGHT_NUMBER_SUFFIX] [varchar](3) NULL,
	[MASTER_SDO] [varchar](8) NULL,
	[BOOKED_PAX] [varchar](20) NULL,
	[HBS_LEVEL_REQUIRED] [char](1) NULL,
	[WEEKDAY] [varchar](1) NULL,
	[HOUR] [varchar](10) NULL,
	[HIGH_RISK] [varchar](1) NULL,
	[ALLOC_OPEN_TIME] [datetime] NULL,
	[ALLOC_CLOSE_TIME] [datetime] NULL,
	[CREATED_BY] [varchar](15) NOT NULL,
	[IS_ALLOCATED] [bit] NOT NULL,
	[CUSTOMS_REQUIRED] [bit] NOT NULL,
	[FLIGHT_TYPE] [varchar](1) NULL
)
GO


