
USE BHSDB
	DECLARE @ID BIGINT
	INSERT INTO [BHSDB].[dbo].[BAGS]
			   ([TIME_STAMP], [RAW_DATA], [ERROR_INDICATOR])
		 VALUES
			   (GETDATE(),'DVC-13611160008FEB10<0D>BSM<0D>CHG<0D>.V/1LTYN<0D>.I/SQ4751/22AUG/KWL/Y<0D>.O/SQ4751/22AUG/KWL/Y<0D>.N/3781134990003<0D>.D/TYN//15MAY/1105//TYN13613<0D>.S/Y/26F/C/002//Y<0D>.W/K/1/10<0D>.P/1CAO/LING/J00/LOO<0D>.L/BMHTQ<0D>.T/13615<0D>.E/RUSH<0D>ENDBSM', '0');
			   
	DECLARE @TIME_STAMP DATETIME = (SELECT MAX(TIME_STAMP) FROM BAGS)
	SELECT @ID = ID FROM BAGS WHERE TIME_STAMP = @TIME_STAMP;		
	
INSERT INTO [BHSDB].[dbo].[BAG_ERROR_BSM]
           ([DATA_ID]
           ,[TIME_STAMP]
           ,[DESCRIPTION])
     VALUES
           (@ID
           ,GETDATE()
           ,'No .F element')
           
           
           
UPDATE [BHSDB].[dbo].[BAGS]
   SET [ERROR_INDICATOR] = '1'
 WHERE ID = @ID