-- ##########################################################################
-- Description: SQL Scripts of creating BHS Solution Database [BHS_LOCALMES].
-- Release#:    R1.0
-- Release On:  09 Dec 2010
-- Filename:    1.1.SYS_CreateDB.sql
-- Histories:
--				R1.0 - Released on 09 Dec 2010.
-- ##########################################################################

PRINT 'STEP 1.1 - Creating BHS Solution Database.'
EXEC msdb.dbo.sp_delete_database_backuphistory @database_name = N'BHS_LOCALMES'

USE [master]
GO

/****** Object:  Database [BHS_LOCALMES]    Script Date: 12/09/2010 14:43:44 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'BHS_LOCALMES')
BEGIN
	PRINT 'WARN: BHS Solution Database has been existed! It will be dropped...'
	DROP DATABASE [BHS_LOCALMES]
END
GO

/****** Object:  Database [BHS_LOCALMES]    Script Date: 12/09/2010 14:43:44 ******/
PRINT 'INFO: Creating the new BHS Solution Database...'
CREATE DATABASE [BHS_LOCALMES] ON  PRIMARY 
( NAME = N'BHS_LOCALMES', FILENAME = N'D:\DBs\BHS_LOCALMES.mdf' , SIZE = 6144KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BHS_LOCALMES_log', FILENAME = N'D:\DBs\BHS_LOCALMES_log.ldf' , SIZE = 15040KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BHS_LOCALMES] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BHS_LOCALMES].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BHS_LOCALMES] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BHS_LOCALMES] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BHS_LOCALMES] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BHS_LOCALMES] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BHS_LOCALMES] SET ARITHABORT OFF 
GO

ALTER DATABASE [BHS_LOCALMES] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BHS_LOCALMES] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [BHS_LOCALMES] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BHS_LOCALMES] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BHS_LOCALMES] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BHS_LOCALMES] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BHS_LOCALMES] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BHS_LOCALMES] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BHS_LOCALMES] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BHS_LOCALMES] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BHS_LOCALMES] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BHS_LOCALMES] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BHS_LOCALMES] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BHS_LOCALMES] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BHS_LOCALMES] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [BHS_LOCALMES] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BHS_LOCALMES] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [BHS_LOCALMES] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BHS_LOCALMES] SET  READ_WRITE 
GO

ALTER DATABASE [BHS_LOCALMES] SET RECOVERY FULL 
GO

ALTER DATABASE [BHS_LOCALMES] SET  MULTI_USER 
GO

ALTER DATABASE [BHS_LOCALMES] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BHS_LOCALMES] SET DB_CHAINING OFF 
GO

PRINT 'INFO: End of STEP 1.1'