-- ##########################################################################
-- Release#		:	R1.00
-- Release On	:	09 Dec 2010
-- Filename		:	2.1.CreateTables.sql
--	01. [AIRLINE_CODE_SHORTCUTS]
--	02. [AIRLINES]
--	03. [AIRPORTS]
--	04. [BAG_INFO]
--	05. [BAG_SORTING]
--	06. [CHUTE_MAPPING]
--	07. [DESTINATIONS]
--	08. [FALLBACK_MAPPING]
--	09. [FALLBACK_TAG_INFO]
--	10. [FLIGHT_PLAN_ALLOC]
--	11. [FLIGHT_PLAN_SORTING]
--	12. [FOUR_DIGITS_FALLBACK_MAPPING]
--	13. [FUNCTION_ALLOC_GANTT]
--	14. [FUNCTION_ALLOC_LIST]
--	15. [FUNCTION_TYPES]
--	16. [HBS_AIRLINE]
--	17. [HBS_COUNTRY]
--	18. [HBS_FLIGHT]
--	19. [HBS_PASSENGER]
--	20. [HBS_POLICY_MANAGEMENT]
--	21. [HBS_SCHEDULE]
--	22. [HBS_TAG_TYPE]
--	23. [ITEM_CUSTOMS_RESULT_TYPES]
--	24. [ITEM_CUSTOMS_SCREENED]
--	25. [ITEM_ENCODE_TYPE]
--	26. [ITEM_ENCODED]
--	27. [ITEM_ENCODING_REQUEST_TYPES]
--	28. [ITEM_INHOUSE_BSM]
--	29. [ITEM_INVENTORY]
--	30. [ITEM_READY]
--	31. [ITEM_REMOVED]
--	32. [ITEM_SCREEN_RESULT_TYPES]
--	33. [ITEM_SCREENED]
--	34. [MES_EVENT]
--	35. [PSEUDO_BSM]
--	36. [ROUTING_TABLE]
--	37. [SORTATION_REASON]
--	38. [SPECIAL_SECURITY_TAG_DESTINATION_MAPPING]
--	39. [SYS_CONFIG]
--	40. [TTS_MES_PRIORITY]
--	41. [MAKEUP_FLIGHT_TYPE_MAPPING]
-- 41. [AIRLINE_CODE_SHORTCUTS_TABLETYPE] - Add storeprocedure AIRLINE_CODE_SHORTCUTS_TABLETYPE
-- 42. [AIRLINES_TABLETYPE] - Add storeprocedure AIRLINES_TABLETYPE
-- 43. [AIRPORTS_TABLETYPE] - Add storeprocedure AIRPORTS_TABLETYPE
-- 44. [BAG_INFO_TABLETYPE] - Add storeprocedure BAG_INFO_TABLETYPE
-- 45. [BAG_SORTING_TABLETYPE] - Add storeprocedure BAG_SORTING_TABLETYPE
-- 46. [CHUTE_MAPPING_TABLETYPE] - Add storeprocedure CHUTE_MAPPING_TABLETYPE
-- 47. [DESTINATIONS_TABLETYPE] - Add storeprocedure DESTINATIONS_TABLETYPE
-- 48. [FALLBACK_MAPPING_TABLETYPE] - Add storeprocedure FALLBACK_MAPPING_TABLETYPE
-- 49. [FALLBACK_TAG_INFO_TABLETYPE] - Add storeprocedure FALLBACK_TAG_INFO_TABLETYPE
-- 50. [FLIGHT_PLAN_ALLOC_TABLETYPE] - Add storeprocedure FLIGHT_PLAN_ALLOC_TABLETYPE
-- 51. [FLIGHT_PLAN_SORTING_TABLETYPE] - Add storeprocedure FLIGHT_PLAN_SORTING_TABLETYPE
-- 52. [FOUR_DIGITS_FALLBACK_MAPPING_TABLETYPE] - Add storeprocedure FOUR_DIGITS_FALLBACK_MAPPING_TABLETYPE
-- 53. [FUNCTION_ALLOC_GANTT_TABLETYPE] - Add storeprocedure FUNCTION_ALLOC_GANTT_TABLETYPE
-- 54. [FUNCTION_ALLOC_LIST_TABLETYPE] - Add storeprocedure FUNCTION_ALLOC_LIST_TABLETYPE
-- 55. [FUNCTION_TYPES_TABLETYPE] - Add storeprocedure FUNCTION_TYPES_TABLETYPE
-- 56. [HBS_AIRLINE_TABLETYPE] - Add storeprocedure HBS_AIRLINE_TABLETYPE
-- 57. [HBS_COUNTRY_TABLETYPE] - Add storeprocedure HBS_COUNTRY_TABLETYPE
-- 58. [HBS_FLIGHT_TABLETYPE] - Add storeprocedure HBS_FLIGHT_TABLETYPE
-- 59. [HBS_PASSENGER_TABLETYPE] - Add storeprocedure HBS_PASSENGER_TABLETYPE
-- 60. [HBS_POLICY_MANAGEMENT_TABLETYPE] - Add storeprocedure HBS_POLICY_MANAGEMENT_TABLETYPE
-- 61. [HBS_SCHEDULE_TABLETYPE] - Add storeprocedure HBS_SCHEDULE_TABLETYPE
-- 62. [HBS_TAG_TYPE_TABLETYPE] - Add storeprocedure HBS_TAG_TYPE_TABLETYPE
-- 63. [PSEUDO_BSM_TABLETYPE] - Add storeprocedure PSEUDO_BSM_TABLETYPE
-- 64. [ROUTING_TABLE_TABLETYPE] - Add storeprocedure ROUTING_TABLE_TABLETYPE
-- 65. [SORTATION_REASON_TABLETYPE] - Add storeprocedure SORTATION_REASON_TABLETYPE
-- 66. [SPECIAL_SECURITY_TAG_DESTINATION_MAPPING_TABLETYPE] - Add storeprocedure SPECIAL_SECURITY_TAG_DESTINATION_MAPPING_TABLETYPE
-- 67. [SYS_CONFIG_TABLETYPE] - Add storeprocedure SYS_CONFIG_TABLETYPE
-- 68. [TTS_MES_PRIORITY_TABLETYPE] - Add storeprocedure TTS_MES_PRIORITY_TABLETYPE
-- ##########################################################################

USE [BHS_LOCALMES]
GO

PRINT 'INFO: STEP2 - Creat BHS Solution Database Tables'
PRINT 'INFO: .'
PRINT 'INFO: .'
PRINT 'INFO: .'
GO
PRINT 'INFO: Begining of Drop Existing Tables...'
GO

/****** Object:  ForeignKey [FK_HBS_POLICY_MANAGEMENT_HBS_TAG_TYPE]    Script Date: 12/09/2010 15:03:16 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_HBS_POLICY_MANAGEMENT_HBS_TAG_TYPE]') AND parent_object_id = OBJECT_ID(N'[dbo].[HBS_POLICY_MANAGEMENT]'))
ALTER TABLE [dbo].[HBS_POLICY_MANAGEMENT] DROP CONSTRAINT [FK_HBS_POLICY_MANAGEMENT_HBS_TAG_TYPE]
GO
/****** Object:  ForeignKey [FK_HBS_SCHEDULE_HBS_POLICY_MANAGEMENT]    Script Date: 12/09/2010 15:03:16 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_HBS_SCHEDULE_HBS_POLICY_MANAGEMENT]') AND parent_object_id = OBJECT_ID(N'[dbo].[HBS_SCHEDULE]'))
ALTER TABLE [dbo].[HBS_SCHEDULE] DROP CONSTRAINT [FK_HBS_SCHEDULE_HBS_POLICY_MANAGEMENT]
GO
/****** Object:  ForeignKey [FK_ITEM_CUSTOMS_SCREENED_RESULT_TYPE]    Script Date: 12/09/2010 15:03:16 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ITEM_CUSTOMS_SCREENED_RESULT_TYPE]') AND parent_object_id = OBJECT_ID(N'[dbo].[ITEM_CUSTOMS_SCREENED]'))
ALTER TABLE [dbo].[ITEM_CUSTOMS_SCREENED] DROP CONSTRAINT [FK_ITEM_CUSTOMS_SCREENED_RESULT_TYPE]
GO
/****** Object:  ForeignKey [FK_ITEM_ENCODED_TYPE]    Script Date: 12/09/2010 15:03:16 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ITEM_ENCODED_TYPE]') AND parent_object_id = OBJECT_ID(N'[dbo].[ITEM_ENCODED]'))
ALTER TABLE [dbo].[ITEM_ENCODED] DROP CONSTRAINT [FK_ITEM_ENCODED_TYPE]
GO
/****** Object:  ForeignKey [FK_ITEM_SCREENED_RESULT_TYPE]    Script Date: 12/09/2010 15:03:17 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ITEM_SCREENED_RESULT_TYPE]') AND parent_object_id = OBJECT_ID(N'[dbo].[ITEM_SCREENED]'))
ALTER TABLE [dbo].[ITEM_SCREENED] DROP CONSTRAINT [FK_ITEM_SCREENED_RESULT_TYPE]
GO
/****** Object:  Table [dbo].[HBS_SCHEDULE]    Script Date: 12/09/2010 15:03:16 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_HBS_SCHEDULE_HBS_POLICY_MANAGEMENT]') AND parent_object_id = OBJECT_ID(N'[dbo].[HBS_SCHEDULE]'))
ALTER TABLE [dbo].[HBS_SCHEDULE] DROP CONSTRAINT [FK_HBS_SCHEDULE_HBS_POLICY_MANAGEMENT]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[HBS_SCHEDULE]') AND type in (N'U'))
DROP TABLE [dbo].[HBS_SCHEDULE]
GO
/****** Object:  Table [dbo].[HBS_POLICY_MANAGEMENT]    Script Date: 12/09/2010 15:03:16 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_HBS_POLICY_MANAGEMENT_HBS_TAG_TYPE]') AND parent_object_id = OBJECT_ID(N'[dbo].[HBS_POLICY_MANAGEMENT]'))
ALTER TABLE [dbo].[HBS_POLICY_MANAGEMENT] DROP CONSTRAINT [FK_HBS_POLICY_MANAGEMENT_HBS_TAG_TYPE]
GO
IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_HBS_POLICY_MANAGEMENT_IS_ENABLED]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[HBS_POLICY_MANAGEMENT] DROP CONSTRAINT [DF_HBS_POLICY_MANAGEMENT_IS_ENABLED]
END
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[HBS_POLICY_MANAGEMENT]') AND type in (N'U'))
DROP TABLE [dbo].[HBS_POLICY_MANAGEMENT]
GO
/****** Object:  Table [dbo].[ITEM_CUSTOMS_SCREENED]    Script Date: 12/09/2010 15:03:16 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ITEM_CUSTOMS_SCREENED_RESULT_TYPE]') AND parent_object_id = OBJECT_ID(N'[dbo].[ITEM_CUSTOMS_SCREENED]'))
ALTER TABLE [dbo].[ITEM_CUSTOMS_SCREENED] DROP CONSTRAINT [FK_ITEM_CUSTOMS_SCREENED_RESULT_TYPE]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ITEM_CUSTOMS_SCREENED]') AND type in (N'U'))
DROP TABLE [dbo].[ITEM_CUSTOMS_SCREENED]
GO
/****** Object:  Table [dbo].[ITEM_ENCODED]    Script Date: 12/09/2010 15:03:16 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ITEM_ENCODED_TYPE]') AND parent_object_id = OBJECT_ID(N'[dbo].[ITEM_ENCODED]'))
ALTER TABLE [dbo].[ITEM_ENCODED] DROP CONSTRAINT [FK_ITEM_ENCODED_TYPE]
GO
IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__ITEM_ENCO__SORT___29AC2CE0]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[ITEM_ENCODED] DROP CONSTRAINT [DF__ITEM_ENCO__SORT___29AC2CE0]
END
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ITEM_ENCODED]') AND type in (N'U'))
DROP TABLE [dbo].[ITEM_ENCODED]
GO
/****** Object:  Table [dbo].[ITEM_SCREENED]    Script Date: 12/09/2010 15:03:17 ******/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ITEM_SCREENED_RESULT_TYPE]') AND parent_object_id = OBJECT_ID(N'[dbo].[ITEM_SCREENED]'))
ALTER TABLE [dbo].[ITEM_SCREENED] DROP CONSTRAINT [FK_ITEM_SCREENED_RESULT_TYPE]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ITEM_SCREENED]') AND type in (N'U'))
DROP TABLE [dbo].[ITEM_SCREENED]
GO
/****** Object:  Table [dbo].[MES_EVENT]    Script Date: 12/09/2010 15:03:17 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MES_EVENT]') AND type in (N'U'))
DROP TABLE [dbo].[MES_EVENT]
GO
/****** Object:  Table [dbo].[PSEUDO_BSM]    Script Date: 12/09/2010 15:03:17 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PSEUDO_BSM]') AND type in (N'U'))
DROP TABLE [dbo].[PSEUDO_BSM]
GO
/****** Object:  Table [dbo].[ROUTING_TABLE]    Script Date: 12/09/2010 15:03:17 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ROUTING_TABLE]') AND type in (N'U'))
DROP TABLE [dbo].[ROUTING_TABLE]
GO
/****** Object:  Table [dbo].[SORTATION_REASON]    Script Date: 12/09/2010 15:03:17 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SORTATION_REASON]') AND type in (N'U'))
DROP TABLE [dbo].[SORTATION_REASON]
GO
/****** Object:  Table [dbo].[SPECIAL_SECURITY_TAG_DESTINATION_MAPPING]    Script Date: 12/09/2010 15:03:17 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SPECIAL_SECURITY_TAG_DESTINATION_MAPPING]') AND type in (N'U'))
DROP TABLE [dbo].[SPECIAL_SECURITY_TAG_DESTINATION_MAPPING]
GO
/****** Object:  Table [dbo].[SYS_CONFIG]    Script Date: 12/09/2010 15:03:17 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SYS_CONFIG]') AND type in (N'U'))
DROP TABLE [dbo].[SYS_CONFIG]
GO
/****** Object:  Table [dbo].[TTS_MES_PRIORITY]    Script Date: 12/09/2010 15:03:17 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TTS_MES_PRIORITY]') AND type in (N'U'))
DROP TABLE [dbo].[TTS_MES_PRIORITY]
GO
/****** Object:  Table [dbo].[ITEM_ENCODING_REQUEST_TYPES]    Script Date: 12/09/2010 15:03:16 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ITEM_ENCODING_REQUEST_TYPES]') AND type in (N'U'))
DROP TABLE [dbo].[ITEM_ENCODING_REQUEST_TYPES]
GO
/****** Object:  Table [dbo].[ITEM_INHOUSE_BSM]    Script Date: 12/09/2010 15:03:16 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ITEM_INHOUSE_BSM]') AND type in (N'U'))
DROP TABLE [dbo].[ITEM_INHOUSE_BSM]
GO
/****** Object:  Table [dbo].[ITEM_INVENTORY]    Script Date: 12/09/2010 15:03:16 ******/
IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_ITEM_INVENTORY_COMPARTMENT_ID]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[ITEM_INVENTORY] DROP CONSTRAINT [DF_ITEM_INVENTORY_COMPARTMENT_ID]
END
GO
IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_ITEM_INVENTORY_LICENSE_PLATE]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[ITEM_INVENTORY] DROP CONSTRAINT [DF_ITEM_INVENTORY_LICENSE_PLATE]
END
GO
IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_ITEM_INVENTORY_AIRLINE]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[ITEM_INVENTORY] DROP CONSTRAINT [DF_ITEM_INVENTORY_AIRLINE]
END
GO
IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_ITEM_INVENTORY_FLIGHT_NUMBER]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[ITEM_INVENTORY] DROP CONSTRAINT [DF_ITEM_INVENTORY_FLIGHT_NUMBER]
END
GO
IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_ITEM_INVENTORY_STD]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[ITEM_INVENTORY] DROP CONSTRAINT [DF_ITEM_INVENTORY_STD]
END
GO
IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_ITEM_INVENTORY_ALLOCATION_OPEN]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[ITEM_INVENTORY] DROP CONSTRAINT [DF_ITEM_INVENTORY_ALLOCATION_OPEN]
END
GO
IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_ITEM_INVENTORY_RUSH]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[ITEM_INVENTORY] DROP CONSTRAINT [DF_ITEM_INVENTORY_RUSH]
END
GO
IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_ITEM_INVENTORY_TIME_STAMP]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[ITEM_INVENTORY] DROP CONSTRAINT [DF_ITEM_INVENTORY_TIME_STAMP]
END
GO
IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_ITEM_INVENTORY_STATION_NAME]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[ITEM_INVENTORY] DROP CONSTRAINT [DF_ITEM_INVENTORY_STATION_NAME]
END
GO
IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_ITEM_INVENTORY_RETRIEVED_TIME]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[ITEM_INVENTORY] DROP CONSTRAINT [DF_ITEM_INVENTORY_RETRIEVED_TIME]
END
GO
IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_ITEM_INVENTORY_RETRIEVED]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[ITEM_INVENTORY] DROP CONSTRAINT [DF_ITEM_INVENTORY_RETRIEVED]
END
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ITEM_INVENTORY]') AND type in (N'U'))
DROP TABLE [dbo].[ITEM_INVENTORY]
GO
/****** Object:  Table [dbo].[ITEM_READY]    Script Date: 12/09/2010 15:03:16 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ITEM_READY]') AND type in (N'U'))
DROP TABLE [dbo].[ITEM_READY]
GO
/****** Object:  Table [dbo].[ITEM_REMOVED]    Script Date: 12/09/2010 15:03:16 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ITEM_REMOVED]') AND type in (N'U'))
DROP TABLE [dbo].[ITEM_REMOVED]
GO
/****** Object:  Table [dbo].[ITEM_SCREEN_RESULT_TYPES]    Script Date: 12/09/2010 15:03:16 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ITEM_SCREEN_RESULT_TYPES]') AND type in (N'U'))
DROP TABLE [dbo].[ITEM_SCREEN_RESULT_TYPES]
GO
/****** Object:  Table [dbo].[ITEM_ENCODE_TYPE]    Script Date: 12/09/2010 15:03:16 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ITEM_ENCODE_TYPE]') AND type in (N'U'))
DROP TABLE [dbo].[ITEM_ENCODE_TYPE]
GO
/****** Object:  Table [dbo].[HBS_TAG_TYPE]    Script Date: 12/09/2010 15:03:16 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[HBS_TAG_TYPE]') AND type in (N'U'))
DROP TABLE [dbo].[HBS_TAG_TYPE]
GO
/****** Object:  Table [dbo].[ITEM_CUSTOMS_RESULT_TYPES]    Script Date: 12/09/2010 15:03:16 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ITEM_CUSTOMS_RESULT_TYPES]') AND type in (N'U'))
DROP TABLE [dbo].[ITEM_CUSTOMS_RESULT_TYPES]
GO
/****** Object:  Table [dbo].[AIRLINE_CODE_SHORTCUTS]    Script Date: 12/09/2010 15:03:14 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[AIRLINE_CODE_SHORTCUTS]') AND type in (N'U'))
DROP TABLE [dbo].[AIRLINE_CODE_SHORTCUTS]
GO
/****** Object:  Table [dbo].[AIRLINES]    Script Date: 12/09/2010 15:03:14 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[AIRLINES]') AND type in (N'U'))
DROP TABLE [dbo].[AIRLINES]
GO
/****** Object:  Table [dbo].[AIRPORTS]    Script Date: 12/09/2010 15:03:14 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[AIRPORTS]') AND type in (N'U'))
DROP TABLE [dbo].[AIRPORTS]
GO
/****** Object:  Table [dbo].[BAG_INFO]    Script Date: 12/09/2010 15:03:14 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BAG_INFO]') AND type in (N'U'))
DROP TABLE [dbo].[BAG_INFO]
GO
/****** Object:  Table [dbo].[BAG_SORTING]    Script Date: 12/09/2010 15:03:14 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BAG_SORTING]') AND type in (N'U'))
DROP TABLE [dbo].[BAG_SORTING]
GO
/****** Object:  Table [dbo].[CHUTE_MAPPING]    Script Date: 12/09/2010 15:03:14 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CHUTE_MAPPING]') AND type in (N'U'))
DROP TABLE [dbo].[CHUTE_MAPPING]
GO
/****** Object:  Table [dbo].[DESTINATIONS]    Script Date: 12/09/2010 15:03:15 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DESTINATIONS]') AND type in (N'U'))
DROP TABLE [dbo].[DESTINATIONS]
GO
/****** Object:  Table [dbo].[FALLBACK_MAPPING]    Script Date: 12/09/2010 15:03:15 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FALLBACK_MAPPING]') AND type in (N'U'))
DROP TABLE [dbo].[FALLBACK_MAPPING]
GO
/****** Object:  Table [dbo].[FALLBACK_TAG_INFO]    Script Date: 12/09/2010 15:03:15 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FALLBACK_TAG_INFO]') AND type in (N'U'))
DROP TABLE [dbo].[FALLBACK_TAG_INFO]
GO
/****** Object:  Table [dbo].[FLIGHT_PLAN_ALLOC]    Script Date: 12/09/2010 15:03:15 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FLIGHT_PLAN_ALLOC]') AND type in (N'U'))
DROP TABLE [dbo].[FLIGHT_PLAN_ALLOC]
GO
/****** Object:  Table [dbo].[FLIGHT_PLAN_SORTING]    Script Date: 12/09/2010 15:03:15 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FLIGHT_PLAN_SORTING]') AND type in (N'U'))
DROP TABLE [dbo].[FLIGHT_PLAN_SORTING]
GO
/****** Object:  Table [dbo].[FOUR_DIGITS_FALLBACK_MAPPING]    Script Date: 12/09/2010 15:03:15 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FOUR_DIGITS_FALLBACK_MAPPING]') AND type in (N'U'))
DROP TABLE [dbo].[FOUR_DIGITS_FALLBACK_MAPPING]
GO
/****** Object:  Table [dbo].[FUNCTION_ALLOC_GANTT]    Script Date: 12/09/2010 15:03:15 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FUNCTION_ALLOC_GANTT]') AND type in (N'U'))
DROP TABLE [dbo].[FUNCTION_ALLOC_GANTT]
GO
/****** Object:  Table [dbo].[FUNCTION_ALLOC_LIST]    Script Date: 12/09/2010 15:03:15 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FUNCTION_ALLOC_LIST]') AND type in (N'U'))
DROP TABLE [dbo].[FUNCTION_ALLOC_LIST]
GO
/****** Object:  Table [dbo].[FUNCTION_TYPES]    Script Date: 12/09/2010 15:03:15 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FUNCTION_TYPES]') AND type in (N'U'))
DROP TABLE [dbo].[FUNCTION_TYPES]
GO
/****** Object:  Table [dbo].[HBS_AIRLINE]    Script Date: 12/09/2010 15:03:15 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[HBS_AIRLINE]') AND type in (N'U'))
DROP TABLE [dbo].[HBS_AIRLINE]
GO
/****** Object:  Table [dbo].[HBS_COUNTRY]    Script Date: 12/09/2010 15:03:15 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[HBS_COUNTRY]') AND type in (N'U'))
DROP TABLE [dbo].[HBS_COUNTRY]
GO
/****** Object:  Table [dbo].[HBS_FLIGHT]    Script Date: 12/09/2010 15:03:15 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[HBS_FLIGHT]') AND type in (N'U'))
DROP TABLE [dbo].[HBS_FLIGHT]
GO
/****** Object:  Table [dbo].[HBS_PASSENGER]    Script Date: 12/09/2010 15:03:15 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[HBS_PASSENGER]') AND type in (N'U'))
DROP TABLE [dbo].[HBS_PASSENGER]
GO
/****** Object:  Table [dbo].[MAKEUP_FLIGHT_TYPE_MAPPING]    Script Date: 01/19/2011 11:12:10 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MAKEUP_FLIGHT_TYPE_MAPPING]') AND type in (N'U'))
DROP TABLE [dbo].[MAKEUP_FLIGHT_TYPE_MAPPING]
GO

PRINT 'INFO: End of Drop Existing Tables...'
GO
PRINT 'INFO: Begining of Creating Tables...'
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[HBS_PASSENGER](
	[ID] [bigint] NOT NULL,
	[SURNAME] [nvarchar](30) NOT NULL,
	[GIVEN_NAME] [nvarchar](30) NULL,
	[ADDITIONAL_GIVEN_NAME] [nvarchar](100) NULL,
	[LEVEL] [varchar](1) NOT NULL,
	[DESCRIPTION] [nvarchar](100) NULL,
	[SYS_ACTION] [varchar](50) NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[HBS_FLIGHT](
	[ID] [varchar](10) NOT NULL,
	[LEVEL] [varchar](1) NOT NULL,
	[DESCRIPTION] [nvarchar](100) NULL,
	[SYS_ACTION] [varchar](50) NULL,
 CONSTRAINT [PK_HBS_FLIGHT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[HBS_COUNTRY](
	[ID] [nvarchar](50) NOT NULL,
	[LEVEL] [varchar](1) NOT NULL,
	[DESCRIPTION] [nvarchar](100) NULL,
	[SYS_ACTION] [varchar](50) NULL,
 CONSTRAINT [PK_HBS_COUNTRY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[HBS_AIRLINE](
	[ID] [varchar](3) NOT NULL,
	[LEVEL] [varchar](1) NOT NULL,
	[DESCRIPTION] [nvarchar](100) NULL,
	[SYS_ACTION] [varchar](50) NULL,
 CONSTRAINT [PK_HBS_AIRLINE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FUNCTION_TYPES](
	[TYPE] [varchar](4) NOT NULL,
	[GROUP] [varchar](5) NOT NULL,
	[DESCRIPTION] [nvarchar](100) NOT NULL,
	[IS_ALLOCATED] [bit] NOT NULL,
	[IS_ENABLED] [bit] NOT NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FUNCTION_ALLOC_LIST](
	[ID] [bigint] NOT NULL,
	[TIME_STAMP] [datetime] NOT NULL,
	[FUNCTION_TYPE] [varchar](4) NOT NULL,
	[RESOURCE] [varchar](10) NOT NULL,
	[IS_ENABLED] [bit] NOT NULL,
	[SYS_TAB_NAME] [varchar](20) NOT NULL,
	[SYS_ACTION] [varchar](50) NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FUNCTION_ALLOC_GANTT](
	[ID] [bigint] NOT NULL,
	[TIME_STAMP] [datetime] NOT NULL,
	[FUNCTION_TYPE] [varchar](4) NOT NULL,
	[RESOURCE] [varchar](10) NOT NULL,
	[ALLOC_OPEN_DATETIME] [datetime] NOT NULL,
	[ALLOC_CLOSE_DATETIME] [datetime] NOT NULL,
	[IS_CLOSED] [bit] NOT NULL,
	[EXCEPTION] [varchar](10) NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FOUR_DIGITS_FALLBACK_MAPPING](
	[ID] [varchar](4) NOT NULL,
	[DESTINATION] [varchar](10) NOT NULL,
	[DESCRIPTION] [nvarchar](100) NULL,
	[SYS_ACTION] [varchar](50) NULL,
 CONSTRAINT [PK_FOUR_DIGITS_FALLBACK_MAPPING] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FLIGHT_PLAN_SORTING](
	[TIME_STAMP] [datetime] NOT NULL,
	[DATA_ID] [bigint] NULL,
	[AIRLINE] [varchar](3) NOT NULL,
	[FLIGHT_NUMBER] [varchar](5) NOT NULL,
	[FLIGHT_NUMBER_SUFFIX] [varchar](3) NULL,
	[HANDLER] [varchar](20) NULL,
	[SDO] [datetime] NOT NULL,
	[STO] [varchar](4) NULL,
	[EDO] [datetime] NULL,
	[ETO] [varchar](4) NULL,
	[ADO] [datetime] NULL,
	[ATO] [varchar](4) NULL,
	[IDO] [datetime] NULL,
	[ITO] [varchar](4) NULL,
	[BLOCK_OFF_TIME] [varchar](14) NULL,
	[FINAL_DEST] [varchar](3) NULL,
	[DEST1] [varchar](3) NULL,
	[DEST2] [varchar](3) NULL,
	[DEST3] [varchar](3) NULL,
	[DEST4] [varchar](3) NULL,
	[DEST5] [varchar](3) NULL,
	[CANCELLED] [varchar](1) NULL,
	[AIRCRAFT_TYPE] [varchar](4) NULL,
	[HANDLER_SPECIFIC_DESC] [varchar](12) NULL,
	[AIRCRAFT_VERSION] [varchar](12) NULL,
	[TERMINAL] [varchar](5) NULL,
	[CHECKIN_AREA] [varchar](10) NULL,
	[CHECKIN_STATUS] [varchar](10) NULL,
	[PUBLIC_REMARK_CODE] [varchar](10) NULL,
	[PIER] [varchar](5) NULL,
	[GATE] [varchar](5) NULL,
	[PARKING_STAND] [varchar](5) NULL,
	[NATURE] [varchar](15) NULL,
	[SORTING_DEST1] [varchar](10) NULL,
	[SORTING_DEST2] [varchar](10) NULL,
	[GENERAL_PURPOSE] [varchar](40) NULL,
	[FI_EXCEPTION] [varchar](10) NULL,
	[MASTER_AIRLINE] [varchar](3) NULL,
	[MASTER_FLIGHT_NUMBER] [varchar](5) NULL,
	[MASTER_FLIGHT_NUMBER_SUFFIX] [varchar](3) NULL,
	[MASTER_SDO] [varchar](8) NULL,
	[BOOKED_PAX] [varchar](20) NULL,
	[HBS_LEVEL_REQUIRED] [char](1) NULL,
	[WEEKDAY] [varchar](1) NULL,
	[HOUR] [varchar](10) NULL,
	[HIGH_RISK] [varchar](1) NULL,
	[ALLOC_OPEN_TIME] [datetime] NULL,
	[ALLOC_CLOSE_TIME] [datetime] NULL,
	[CREATED_BY] [varchar](15) NOT NULL,
	[IS_ALLOCATED] [bit] NOT NULL CONSTRAINT [DF_FPA_IS_ALLOCATED]  DEFAULT ((0)),
	[CUSTOMS_REQUIRED] [bit] NOT NULL CONSTRAINT [DF_FPA_CUSTOMS_REQUIRED]  DEFAULT ((1)),
	[FLIGHT_TYPE] [varchar](1) NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FLIGHT_PLAN_ALLOC](
	[ID] [bigint] NOT NULL,
	[AIRLINE] [varchar](3) NOT NULL,
	[FLIGHT_NUMBER] [varchar](5) NOT NULL,
	[SDO] [datetime] NOT NULL,
	[STO] [varchar](4) NOT NULL,
	[RESOURCE] [varchar](10) NOT NULL,
	[WEEKDAY] [char](1) NOT NULL,
	[EDO] [datetime] NULL,
	[ETO] [varchar](4) NULL,
	[ADO] [datetime] NULL,
	[ATO] [varchar](4) NULL,
	[IDO] [datetime] NULL,
	[ITO] [varchar](4) NULL,
	[TRAVEL_CLASS] [varchar](1) NOT NULL,
	[FLIGHT_DESTINATION] [varchar](3) NOT NULL,
	[BAG_TYPE] [varchar](10) NOT NULL,
	[TRANSFER] [varchar](10) NOT NULL,
	[COMMENT_ID] [bigint] NULL,
	[HIGH_RISK] [char](1) NULL,
	[HBS_LEVEL_REQUIRED] [char](1) NULL,
	[EARLY_OPEN_OFFSET] [varchar](5) NULL,
	[EARLY_OPEN_ENABLED] [bit] NULL,
	[ALLOC_OPEN_OFFSET] [varchar](5) NOT NULL,
	[ALLOC_OPEN_RELATED] [varchar](4) NOT NULL,
	[ALLOC_CLOSE_OFFSET] [varchar](5) NOT NULL,
	[ALLOC_CLOSE_RELATED] [varchar](4) NOT NULL,
	[RUSH_DURATION] [varchar](5) NULL,
	[SCHEME_TYPE] [varchar](2) NULL,
	[CREATED_BY] [varchar](15) NOT NULL,
	[TIME_STAMP] [datetime] NOT NULL,
	[HOUR] [varchar](2) NULL,
	[IS_MANUAL_CLOSE] [bit] NOT NULL,
	[IS_CLOSED] [bit] NOT NULL,
	[IS_MISS_TEMPLATE_FLIGHT] [bit] NOT NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FALLBACK_TAG_INFO](
	[ID] [bigint] NOT NULL,
	[TIME_STAMP] [datetime] NOT NULL,
	[NO_OF_FALLBACK] [varchar](2) NOT NULL,
	[FALLBACK_NO_1] [varchar](2) NOT NULL,
	[DESTINATION_1A] [varchar](4) NOT NULL,
	[DESTINATION_1B] [varchar](4) NOT NULL,
	[FLIGHT_TYPE_1] [varchar](1) NOT NULL,
	[FALLBACK_NO_2] [varchar](2) NULL,
	[DESTINATION_2A] [varchar](4) NULL,
	[DESTINATION_2B] [varchar](4) NULL,
	[FLIGHT_TYPE_2] [varchar](1) NULL,
	[FALLBACK_NO_3] [varchar](2) NULL,
	[DESTINATION_3A] [varchar](4) NULL,
	[DESTINATION_3B] [varchar](4) NULL,
	[FLIGHT_TYPE_3] [varchar](1) NULL,
	[FALLBACK_NO_4] [varchar](2) NULL,
	[DESTINATION_4A] [varchar](4) NULL,
	[DESTINATION_4B] [varchar](4) NULL,
	[FLIGHT_TYPE_4] [varchar](1) NULL,
	[FALLBACK_NO_5] [varchar](2) NULL,
	[DESTINATION_5A] [varchar](4) NULL,
	[DESTINATION_5B] [varchar](4) NULL,
	[FLIGHT_TYPE_5] [varchar](1) NULL,
	[FALLBACK_NO_6] [varchar](2) NULL,
	[DESTINATION_6A] [varchar](4) NULL,
	[DESTINATION_6B] [varchar](4) NULL,
	[FLIGHT_TYPE_6] [varchar](1) NULL,
	[FALLBACK_NO_7] [varchar](2) NULL,
	[DESTINATION_7A] [varchar](4) NULL,
	[DESTINATION_7B] [varchar](4) NULL,
	[FLIGHT_TYPE_7] [varchar](1) NULL,
	[FALLBACK_NO_8] [varchar](2) NULL,
	[DESTINATION_8A] [varchar](4) NULL,
	[DESTINATION_8B] [varchar](4) NULL,
	[FLIGHT_TYPE_8] [varchar](1) NULL,
	[FALLBACK_NO_9] [varchar](2) NULL,
	[DESTINATION_9A] [varchar](4) NULL,
	[DESTINATION_9B] [varchar](4) NULL,
	[FLIGHT_TYPE_9] [varchar](1) NULL,
	[FALLBACK_NO_10] [varchar](2) NULL,
	[DESTINATION_10A] [varchar](4) NULL,
	[DESTINATION_10B] [varchar](4) NULL,
	[FLIGHT_TYPE_10] [varchar](1) NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FALLBACK_MAPPING](
	[ID] [varchar](2) NOT NULL,
	[DESTINATION] [varchar](10) NOT NULL,
	[DESCRIPTION] [nvarchar](100) NULL,
	[SYS_ACTION] [varchar](50) NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DESTINATIONS](
	[DESTINATION] [varchar](10) NOT NULL,
	[SUBSYSTEM] [varchar](10) NOT NULL,
	[DESCRIPTION] [nvarchar](100) NOT NULL,
	[IS_AVAILABLE] [bit] NOT NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CHUTE_MAPPING](
	[CHUTE] [varchar](20) NOT NULL,
	[TTS_ID] [varchar](20) NOT NULL,
	[SORTER] [varchar](10) NOT NULL,
	[DESTINATION] [varchar](20) NOT NULL,
	[IS_AVAILABLE] [bit] NOT NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BAG_SORTING](
	[ID] [bigint] NOT NULL,
	[DATA_ID] [bigint] NULL,
	[TIME_STAMP] [datetime] NOT NULL,
	[DICTIONARY_VERSION] [int] NULL,
	[SOURCE] [varchar](1) NULL,
	[AIRPORT_CODE] [varchar](5) NULL,
	[LICENSE_PLATE] [varchar](10) NOT NULL,
	[AIRLINE] [varchar](3) NULL,
	[FLIGHT_NUMBER] [varchar](5) NULL,
	[SDO] [datetime] NULL,
	[DESTINATION] [varchar](5) NULL,
	[TRAVEL_CLASS] [varchar](1) NULL,
	[INBOUND_AIRLINE] [varchar](3) NULL,
	[INBOUND_FLIGHT_NUMBER] [varchar](5) NULL,
	[INBOUND_SDO] [datetime] NULL,
	[INBOUND_AIRPORT_CODE] [varchar](5) NULL,
	[INBOUND_TRAVEL_CLASS] [varchar](1) NULL,
	[ONWARD_AIRLINE1] [varchar](3) NULL,
	[ONWARD_FLIGHT_NUMBER1] [varchar](5) NULL,
	[ONWARD_SDO1] [datetime] NULL,
	[ONWARD_AIRPORT_CODE1] [varchar](5) NULL,
	[ONWARD_TRAVEL_CLASS1] [varchar](1) NULL,
	[ONWARD_AIRLINE2] [varchar](3) NULL,
	[ONWARD_FLIGHT_NUMBER2] [varchar](5) NULL,
	[ONWARD_SDO2] [datetime] NULL,
	[ONWARD_AIRPORT_CODE2] [varchar](5) NULL,
	[ONWARD_TRAVEL_CLASS2] [varchar](1) NULL,
	[ONWARD_AIRLINE3] [varchar](3) NULL,
	[ONWARD_FLIGHT_NUMBER3] [varchar](5) NULL,
	[ONWARD_SDO3] [datetime] NULL,
	[ONWARD_AIRPORT_CODE3] [varchar](5) NULL,
	[ONWARD_TRAVEL_CLASS3] [varchar](1) NULL,
	[ONWARD_AIRLINE4] [varchar](3) NULL,
	[ONWARD_FLIGHT_NUMBER4] [varchar](5) NULL,
	[ONWARD_SDO4] [datetime] NULL,
	[ONWARD_AIRPORT_CODE4] [varchar](5) NULL,
	[ONWARD_TRAVEL_CLASS4] [varchar](5) NULL,
	[ONWARD_AIRLINE5] [varchar](3) NULL,
	[ONWARD_FLIGHT_NUMBER5] [varchar](5) NULL,
	[ONWARD_SDO5] [datetime] NULL,
	[ONWARD_AIRPORT_CODE5] [varchar](5) NULL,
	[ONWARD_TRAVEL_CLASS5] [varchar](1) NULL,
	[NO_PASSENGER_SAME_SURNAME] [int] NULL,
	[SURNAME] [nvarchar](30) NULL,
	[GIVEN_NAME] [nvarchar](30) NULL,
	[OTHERS_NAME] [nvarchar](100) NULL,
	[BAG_EXCEPTION] [varchar](10) NULL,
	[CHECK_IN_COUNTER] [varchar](10) NULL,
	[CHECK_IN_COUNTER_DESCRIPTION] [varchar](20) NULL,
	[CHECK_IN_TIME_STAMP] [datetime] NULL,
	[CHECK_IN_CARRIAGE_MEDIUM] [varchar](5) NULL,
	[CHECK_IN_TRANSPORT_ID] [varchar](20) NULL,
	[TAG_PRINTER_ID] [varchar](10) NULL,
	[RECONCILIATION_LOAD_AUTHORITY] [varchar](1) NULL,
	[RECONCILIATION_SEAT_NUMBER] [varchar](5) NULL,
	[RECONCILIATION_PASSENGER_STATUS] [varchar](1) NULL,
	[RECONCILIATION_SEQUENCE_NUMBER] [varchar](3) NULL,
	[RECONCILIATION_SECURITY_NUMBER] [varchar](3) NULL,
	[RECONCILIATION_PASSENGER_PROFILES_STATUS] [varchar](1) NULL,
	[RECONCILIATION_TRANSPORT_AUTHORITY] [varchar](1) NULL,
	[RECONCILIATION_BAG_TAG_STATUS] [varchar](1) NULL,
	[HANDLING_TERMINAL] [varchar](10) NULL,
	[HANDLING_BAR] [varchar](10) NULL,
	[HANDLING_GATE] [varchar](10) NULL,
	[WEIGHT_INDICATOR] [varchar](1) NULL,
	[WEIGHT_CHECKED_BAG_NUMBER] [int] NULL,
	[CHECKED_WEIGHT] [int] NULL,
	[UNCHECKED_WEIGHT] [int] NULL,
	[WEIGHT_UNIT] [varchar](2) NULL,
	[WEIGHT_LENGTH] [int] NULL,
	[WEIGHT_WIDTH] [int] NULL,
	[WEIGHT_HEIGHT] [int] NULL,
	[WEIGHT_BAG_TYPE_CODE] [varchar](10) NULL,
	[GROUND_TRANSPORT_EARLIEST_DELIVERY] [datetime] NULL,
	[GROUND_TRANSPORT_LATEST_DELIVERY] [datetime] NULL,
	[GROUND_TRANSPORT_DESCRIPTION] [varchar](200) NULL,
	[FREQUENT_TRAVELLER_ID_NUMBER] [varchar](25) NULL,
	[FREQUENT_TRAVELLER_TIER_ID] [varchar](25) NULL,
	[CORPORATE_NAME] [varchar](20) NULL,
	[AUTOMATED_PNR_ADDRESS] [varchar](20) NULL,
	[MESSAGE_PRINTER_ID] [varchar](10) NULL,
	[INTERNAL_AIRLINE_DATA] [varchar](60) NULL,
	[SECURITY_SCREENING_INSTRUCTION] [varchar](3) NULL,
	[SECURITY_SCREENING_RESULT] [varchar](3) NULL,
	[SECURITY_SCREENING_RESULT_REASON] [varchar](1) NULL,
	[SECURITY_SCREENING_RESULT_METHOD] [varchar](5) NULL,
	[SECURITY_SCREENING_AUTOGRAPH] [varchar](10) NULL,
	[SECURITY_SCREENING_FREE_TEXT] [varchar](40) NULL,
	[HIGH_RISK] [char](1) NULL,
	[HBS_LEVEL_REQUIRED] [char](1) NULL,
	[CREATED_BY] [varchar](15) NOT NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BAG_INFO](
	[TIME_STAMP] [datetime] NOT NULL,
	[INDEX_NO] [varchar](10) NOT NULL,
	[GID] [varchar](10) NOT NULL,
	[LICENSE_PLATE] [varchar](10) NOT NULL,
	[LICENSE_PLATE1] [varchar](10) NULL,
	[LICENSE_PLATE2] [varchar](10) NULL,
	[LICENSE_PLATE3] [varchar](10) NULL,
	[MIN_SECURITY_LEVEL] [varchar](1) NULL,
	[CURRENT_HBS_LEVEL] [varchar](1) NULL,
	[HBS1_RESULT] [varchar](1) NULL,
	[HBS2_RESULT] [varchar](1) NULL,
	[HBS3_RESULT] [varchar](1) NULL,
	[HBS4_RESULT] [varchar](1) NULL,
	[HBS5_RESULT] [varchar](1) NULL,
	[CUSTOMS_RESULT] [varchar](1) NULL,
	[SORT_REASON] [varchar](2) NULL,
	[DEST1] [varchar](20) NULL,
	[DEST2] [varchar](20) NULL,
	[DEST3] [varchar](20) NULL,
	[RECYLE_COUNT] [int] NULL,
	[LAST_LOCATION] [varchar](20) NOT NULL,
	[ENCODED_TYPE] [varchar](2) NULL,
	[OOG] [bit] NOT NULL,
	[EBS] [bit] NOT NULL,
	[DISCHARGED] [bit] NOT NULL,
	[DISAPPEARED] [bit] NOT NULL,
	[SORTED] [bit] NOT NULL,
	[CREATED_BY] [varchar](15) NOT NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[AIRPORTS](
	[CODE_IATA] [varchar](3) NOT NULL,
	[CODE_ICAO] [varchar](4) NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[COUNTRY] [nvarchar](50) NOT NULL,
	[CITY] [nvarchar](30) NOT NULL,
 CONSTRAINT [PK_AIRPORTS] PRIMARY KEY CLUSTERED 
(
	[CODE_IATA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[AIRLINES](
	[CODE_IATA] [varchar](3) NOT NULL,
	[CODE_ICAO] [varchar](3) NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[TICKETING_CODE] [varchar](4) NOT NULL,
	[DESTINATION] [varchar](10) NULL,
	[DESTINATION1] [varchar](10) NULL,
	[RUSH] [varchar](10) NULL,
	[HANDLER] [varchar](3) NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[AIRLINE_CODE_SHORTCUTS](
	[ID] [varchar](15) NOT NULL,
	[AIRLINE] [varchar](3) NULL,
	[DESCRIPTION] [nvarchar](100) NULL,
	[SYS_ACTION] [varchar](50) NOT NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ITEM_CUSTOMS_RESULT_TYPES](
	[TYPE] [varchar](1) NOT NULL,
	[DESCRIPTION] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_ITEM_CUSTOMS_RESULT_TYPES] PRIMARY KEY CLUSTERED 
(
	[TYPE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[HBS_TAG_TYPE](
	[ID] [varchar](10) NOT NULL,
	[DESCRIPTION] [varchar](50) NULL,
 CONSTRAINT [PK_HBS_TAG_TYPE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ITEM_ENCODE_TYPE](
	[ENCODE_TYPE] [varchar](5) NOT NULL,
	[TYPE_DESC] [varchar](50) NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ITEM_SCREEN_RESULT_TYPES](
	[TYPE] [varchar](1) NOT NULL,
	[DESCRIPTION] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_ITEM_SCREEN_RESULT_TYPES] PRIMARY KEY CLUSTERED 
(
	[TYPE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ITEM_REMOVED](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TIME_STAMP] [datetime] NOT NULL,
	[GID] [varchar](10) NOT NULL,
	[LICENSE_PLATE] [varchar](10) NOT NULL,
	[SUBSYSTEM] [varchar](10) NOT NULL,
	[LOCATION] [varchar](20) NOT NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ITEM_READY](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TIME_STAMP] [datetime] NOT NULL,
	[GID] [varchar](10) NOT NULL,
	[LICENSE_PLATE] [varchar](10) NOT NULL,
	[SUBSYSTEM] [varchar](10) NOT NULL,
	[LOCATION] [varchar](20) NOT NULL,
	[INDEX_NO] [varchar](10) NOT NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ITEM_INVENTORY](
	[COMPARTMENT_ID] [varchar](10) NOT NULL,
	[LICENSE_PLATE] [varchar](10) NOT NULL,
	[AIRLINE] [varchar](3) NOT NULL,
	[FLIGHT_NUMBER] [varchar](5) NOT NULL,
	[STD] [datetime] NOT NULL,
	[RETRIEVAL_TIME] [datetime] NOT NULL,
	[RUSH_TIME] [datetime] NOT NULL,
	[TIME_STAMP] [datetime] NOT NULL,
	[STATION_NAME] [varchar](20) NOT NULL,
	[ENTRY_TIME] [datetime] NOT NULL,
	[RETRIEVED] [tinyint] NOT NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ITEM_INHOUSE_BSM](
	[INHOUSEBSM] [varchar](10) NOT NULL,
	[FIRST_DIGIT] [varchar](1) NOT NULL,
	[AIRLINE] [varchar](5) NOT NULL,
	[FLIGHT_NUMBER] [varchar](5) NOT NULL,
	[SDO] [datetime] NOT NULL,
	[DESCRIPTION] [varchar](20) NULL,
	[MES_STATION] [varchar](16) NOT NULL,
	[GENERATED_NUMBER] [varchar](6) NOT NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ITEM_ENCODING_REQUEST_TYPES](
	[TYPE] [varchar](2) NOT NULL,
	[DESCRIPTION] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_ITEM_ENCODING_REQUEST_TYPES] PRIMARY KEY CLUSTERED 
(
	[TYPE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TTS_MES_PRIORITY](
	[SYS_KEY] [varchar](40) NOT NULL,
	[VALUE] [varchar](15) NOT NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SYS_CONFIG](
	[SYS_KEY] [varchar](40) NOT NULL,
	[SYS_VALUE] [varchar](20) NOT NULL,
	[DEFAULT_VALUE] [varchar](20) NOT NULL,
	[LAST_VALUE] [varchar](20) NOT NULL,
	[DESCRIPTION] [nvarchar](80) NOT NULL,
	[VALUE_TOKEN] [varchar](80) NULL,
	[SYS_ACTION] [varchar](50) NULL,
	[GROUP_NAME] [varchar](20) NULL,
	[ORDER_FLAG] [varchar](1) NULL,
	[IS_ENABLED] [bit] NOT NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SPECIAL_SECURITY_TAG_DESTINATION_MAPPING](
	[ID] [varchar](2) NOT NULL,
	[DESTINATION] [varchar](10) NOT NULL,
	[DESCRIPTION] [nvarchar](100) NULL,
	[SYS_ACTION] [varchar](50) NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SORTATION_REASON](
	[REASON] [varchar](2) NOT NULL,
	[DESCRIPTION] [nvarchar](50) NOT NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ROUTING_TABLE](
	[SUBSYSTEM] [varchar](10) NOT NULL,
	[LOCATION] [varchar](20) NOT NULL,
	[DESCRIPTION] [nvarchar](50) NOT NULL,
	[COST] [decimal](4, 0) NOT NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PSEUDO_BSM](
	[TIME_STAMP] [datetime] NOT NULL,
	[LICENSE_PLATE] [varchar](10) NOT NULL,
	[AIRLINE] [varchar](3) NOT NULL,
	[FLIGHT_NUMBER] [varchar](5) NOT NULL,
	[SDO] [datetime] NOT NULL,
	[DESCRITION] [varchar](50) NULL,
	[TYPE] [varchar](10) NOT NULL,
	[CREATED_BY] [varchar](15) NOT NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MES_EVENT](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TIME_STAMP] [datetime] NOT NULL,
	[GID] [varchar](10) NOT NULL,
	[LICENSE_PLATE] [varchar](10) NOT NULL,
	[SUBSYSTEM] [varchar](10) NOT NULL,
	[LOCATION] [varchar](10) NULL,
	[ACTION] [varchar](10) NOT NULL,
	[ACTION_DESC] [varchar](25) NULL,
	[MES_STATION] [varchar](16) NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ITEM_SCREENED](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TIME_STAMP] [datetime] NOT NULL,
	[GID] [varchar](10) NOT NULL,
	[LICENSE_PLATE] [varchar](10) NOT NULL,
	[SUBSYSTEM] [varchar](10) NOT NULL,
	[LOCATION] [varchar](20) NOT NULL,
	[XRAY_ID] [varchar](10) NOT NULL,
	[SCREEN_LEVEL] [char](1) NOT NULL,
	[RESULT_TYPE] [varchar](1) NOT NULL,
 CONSTRAINT [PK_ITEM_SCREEN] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ITEM_ENCODED](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TIME_STAMP] [datetime] NOT NULL,
	[GID] [varchar](10) NOT NULL,
	[LICENSE_PLATE] [varchar](10) NULL,
	[SUBSYSTEM] [varchar](10) NOT NULL,
	[LOCATION] [varchar](20) NOT NULL,
	[DESTINATION] [varchar](20) NOT NULL,
	[ENCODED_TYPE] [varchar](2) NOT NULL,
	[SORT_REASON] [varchar](2) NOT NULL,
	[INDEX_NO] [VARCHAR] (10) NOT NULL,
 CONSTRAINT [PK_ITEM_ENCODED] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ITEM_CUSTOMS_SCREENED](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TIME_STAMP] [datetime] NOT NULL,
	[GID] [varchar](10) NOT NULL,
	[LICENSE_PLATE] [varchar](10) NOT NULL,
	[SUBSYSTEM] [varchar](10) NOT NULL,
	[LOCATION] [varchar](20) NOT NULL,
	[RESULT_TYPE] [varchar](1) NOT NULL,
 CONSTRAINT [PK_ITEM_CUSTOMS_SCREENED] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[HBS_POLICY_MANAGEMENT](
	[ID] [bigint] NOT NULL,
	[HBS_TAG] [varchar](10) NOT NULL,
	[ENABLED] [bit] NOT NULL,
	[TYPE] [varchar](10) NOT NULL,
 CONSTRAINT [PK_HBS_POLICY_MANAGEMENT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HBS_SCHEDULE](
	[ID] [bigint] NOT NULL,
	[START_TIME] [datetime] NOT NULL,
	[END_TIME] [datetime] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MAKEUP_FLIGHT_TYPE_MAPPING]    Script Date: 01/19/2011 11:12:10 ******/
CREATE TABLE [dbo].[MAKEUP_FLIGHT_TYPE_MAPPING](
	[ID] [bigint] NOT NULL,
	[RESOURCE] [varchar](10) NOT NULL,
	[FLIGHT_TYPE] [varchar](1) NOT NULL
) ON [PRIMARY]

ALTER TABLE [dbo].[HBS_POLICY_MANAGEMENT] ADD  CONSTRAINT [DF_HBS_POLICY_MANAGEMENT_IS_ENABLED]  DEFAULT ((0)) FOR [ENABLED]
GO
ALTER TABLE [dbo].[ITEM_ENCODED] ADD  DEFAULT ('') FOR [SORT_REASON]
GO
ALTER TABLE [dbo].[ITEM_INVENTORY] ADD  CONSTRAINT [DF_ITEM_INVENTORY_COMPARTMENT_ID]  DEFAULT ('') FOR [COMPARTMENT_ID]
GO
ALTER TABLE [dbo].[ITEM_INVENTORY] ADD  CONSTRAINT [DF_ITEM_INVENTORY_LICENSE_PLATE]  DEFAULT ('') FOR [LICENSE_PLATE]
GO
ALTER TABLE [dbo].[ITEM_INVENTORY] ADD  CONSTRAINT [DF_ITEM_INVENTORY_AIRLINE]  DEFAULT ('') FOR [AIRLINE]
GO
ALTER TABLE [dbo].[ITEM_INVENTORY] ADD  CONSTRAINT [DF_ITEM_INVENTORY_FLIGHT_NUMBER]  DEFAULT ('') FOR [FLIGHT_NUMBER]
GO
ALTER TABLE [dbo].[ITEM_INVENTORY] ADD  CONSTRAINT [DF_ITEM_INVENTORY_STD]  DEFAULT ('01-Jan-1900') FOR [STD]
GO
ALTER TABLE [dbo].[ITEM_INVENTORY] ADD  CONSTRAINT [DF_ITEM_INVENTORY_ALLOCATION_OPEN]  DEFAULT ('01-Jan-1900') FOR [RETRIEVAL_TIME]
GO
ALTER TABLE [dbo].[ITEM_INVENTORY] ADD  CONSTRAINT [DF_ITEM_INVENTORY_RUSH]  DEFAULT ('01-Jan-1900') FOR [RUSH_TIME]
GO
ALTER TABLE [dbo].[ITEM_INVENTORY] ADD  CONSTRAINT [DF_ITEM_INVENTORY_TIME_STAMP]  DEFAULT (getdate()) FOR [TIME_STAMP]
GO
ALTER TABLE [dbo].[ITEM_INVENTORY] ADD  CONSTRAINT [DF_ITEM_INVENTORY_STATION_NAME]  DEFAULT ('') FOR [STATION_NAME]
GO
ALTER TABLE [dbo].[ITEM_INVENTORY] ADD  CONSTRAINT [DF_ITEM_INVENTORY_RETRIEVED_TIME]  DEFAULT ('01-Jan-1900') FOR [ENTRY_TIME]
GO
ALTER TABLE [dbo].[ITEM_INVENTORY] ADD  CONSTRAINT [DF_ITEM_INVENTORY_RETRIEVED]  DEFAULT ((0)) FOR [RETRIEVED]
GO
ALTER TABLE [dbo].[HBS_POLICY_MANAGEMENT]  WITH CHECK ADD  CONSTRAINT [FK_HBS_POLICY_MANAGEMENT_HBS_TAG_TYPE] FOREIGN KEY([HBS_TAG])
REFERENCES [dbo].[HBS_TAG_TYPE] ([ID])
GO
ALTER TABLE [dbo].[HBS_POLICY_MANAGEMENT] CHECK CONSTRAINT [FK_HBS_POLICY_MANAGEMENT_HBS_TAG_TYPE]
GO
ALTER TABLE [dbo].[HBS_SCHEDULE]  WITH CHECK ADD  CONSTRAINT [FK_HBS_SCHEDULE_HBS_POLICY_MANAGEMENT] FOREIGN KEY([ID])
REFERENCES [dbo].[HBS_POLICY_MANAGEMENT] ([ID])
GO
ALTER TABLE [dbo].[HBS_SCHEDULE] CHECK CONSTRAINT [FK_HBS_SCHEDULE_HBS_POLICY_MANAGEMENT]
GO
ALTER TABLE [dbo].[ITEM_CUSTOMS_SCREENED]  WITH CHECK ADD  CONSTRAINT [FK_ITEM_CUSTOMS_SCREENED_RESULT_TYPE] FOREIGN KEY([RESULT_TYPE])
REFERENCES [dbo].[ITEM_CUSTOMS_RESULT_TYPES] ([TYPE])
GO
ALTER TABLE [dbo].[ITEM_CUSTOMS_SCREENED] CHECK CONSTRAINT [FK_ITEM_CUSTOMS_SCREENED_RESULT_TYPE]
GO
ALTER TABLE [dbo].[ITEM_ENCODED]  WITH NOCHECK ADD  CONSTRAINT [FK_ITEM_ENCODED_TYPE] FOREIGN KEY([ENCODED_TYPE])
REFERENCES [dbo].[ITEM_ENCODING_REQUEST_TYPES] ([TYPE])
GO
ALTER TABLE [dbo].[ITEM_ENCODED] CHECK CONSTRAINT [FK_ITEM_ENCODED_TYPE]
GO
ALTER TABLE [dbo].[ITEM_SCREENED]  WITH CHECK ADD  CONSTRAINT [FK_ITEM_SCREENED_RESULT_TYPE] FOREIGN KEY([RESULT_TYPE])
REFERENCES [dbo].[ITEM_SCREEN_RESULT_TYPES] ([TYPE])
GO
ALTER TABLE [dbo].[ITEM_SCREENED] CHECK CONSTRAINT [FK_ITEM_SCREENED_RESULT_TYPE]
GO

USE [BHS_LOCALMES]
GO
IF  EXISTS (SELECT * FROM sys.types st JOIN sys.schemas ss ON st.schema_id = ss.schema_id WHERE st.name = N'AIRLINE_CODE_SHORTCUTS_TABLETYPE' AND ss.name = N'dbo')
DROP TYPE [dbo].[AIRLINE_CODE_SHORTCUTS_TABLETYPE]
GO
IF  EXISTS (SELECT * FROM sys.types st JOIN sys.schemas ss ON st.schema_id = ss.schema_id WHERE st.name = N'AIRLINES_TABLETYPE' AND ss.name = N'dbo')
DROP TYPE [dbo].[AIRLINES_TABLETYPE]
GO
IF  EXISTS (SELECT * FROM sys.types st JOIN sys.schemas ss ON st.schema_id = ss.schema_id WHERE st.name = N'AIRPORTS_TABLETYPE' AND ss.name = N'dbo')
DROP TYPE [dbo].[AIRPORTS_TABLETYPE]
GO
IF  EXISTS (SELECT * FROM sys.types st JOIN sys.schemas ss ON st.schema_id = ss.schema_id WHERE st.name = N'BAG_INFO_TABLETYPE' AND ss.name = N'dbo')
DROP TYPE [dbo].[BAG_INFO_TABLETYPE]
GO
IF  EXISTS (SELECT * FROM sys.types st JOIN sys.schemas ss ON st.schema_id = ss.schema_id WHERE st.name = N'BAG_SORTING_TABLETYPE' AND ss.name = N'dbo')
DROP TYPE [dbo].[BAG_SORTING_TABLETYPE]
GO
IF  EXISTS (SELECT * FROM sys.types st JOIN sys.schemas ss ON st.schema_id = ss.schema_id WHERE st.name = N'CHUTE_MAPPING_TABLETYPE' AND ss.name = N'dbo')
DROP TYPE [dbo].[CHUTE_MAPPING_TABLETYPE]
GO
IF  EXISTS (SELECT * FROM sys.types st JOIN sys.schemas ss ON st.schema_id = ss.schema_id WHERE st.name = N'DESTINATIONS_TABLETYPE' AND ss.name = N'dbo')
DROP TYPE [dbo].[DESTINATIONS_TABLETYPE]
GO
IF  EXISTS (SELECT * FROM sys.types st JOIN sys.schemas ss ON st.schema_id = ss.schema_id WHERE st.name = N'FALLBACK_MAPPING_TABLETYPE' AND ss.name = N'dbo')
DROP TYPE [dbo].[FALLBACK_MAPPING_TABLETYPE]
GO
IF  EXISTS (SELECT * FROM sys.types st JOIN sys.schemas ss ON st.schema_id = ss.schema_id WHERE st.name = N'FALLBACK_TAG_INFO_TABLETYPE' AND ss.name = N'dbo')
DROP TYPE [dbo].[FALLBACK_TAG_INFO_TABLETYPE]
GO
IF  EXISTS (SELECT * FROM sys.types st JOIN sys.schemas ss ON st.schema_id = ss.schema_id WHERE st.name = N'FLIGHT_PLAN_ALLOC_TABLETYPE' AND ss.name = N'dbo')
DROP TYPE [dbo].[FLIGHT_PLAN_ALLOC_TABLETYPE]
GO
IF  EXISTS (SELECT * FROM sys.types st JOIN sys.schemas ss ON st.schema_id = ss.schema_id WHERE st.name = N'FLIGHT_PLAN_SORTING_TABLETYPE' AND ss.name = N'dbo')
DROP TYPE [dbo].[FLIGHT_PLAN_SORTING_TABLETYPE]
GO
IF  EXISTS (SELECT * FROM sys.types st JOIN sys.schemas ss ON st.schema_id = ss.schema_id WHERE st.name = N'FOUR_DIGITS_FALLBACK_MAPPING_TABLETYPE' AND ss.name = N'dbo')
DROP TYPE [dbo].[FOUR_DIGITS_FALLBACK_MAPPING_TABLETYPE]
GO
IF  EXISTS (SELECT * FROM sys.types st JOIN sys.schemas ss ON st.schema_id = ss.schema_id WHERE st.name = N'FUNCTION_ALLOC_GANTT_TABLETYPE' AND ss.name = N'dbo')
DROP TYPE [dbo].[FUNCTION_ALLOC_GANTT_TABLETYPE]
GO
IF  EXISTS (SELECT * FROM sys.types st JOIN sys.schemas ss ON st.schema_id = ss.schema_id WHERE st.name = N'FUNCTION_ALLOC_LIST_TABLETYPE' AND ss.name = N'dbo')
DROP TYPE [dbo].[FUNCTION_ALLOC_LIST_TABLETYPE]
GO
IF  EXISTS (SELECT * FROM sys.types st JOIN sys.schemas ss ON st.schema_id = ss.schema_id WHERE st.name = N'FUNCTION_TYPES_TABLETYPE' AND ss.name = N'dbo')
DROP TYPE [dbo].[FUNCTION_TYPES_TABLETYPE]
GO
IF  EXISTS (SELECT * FROM sys.types st JOIN sys.schemas ss ON st.schema_id = ss.schema_id WHERE st.name = N'HBS_AIRLINE_TABLETYPE' AND ss.name = N'dbo')
DROP TYPE [dbo].[HBS_AIRLINE_TABLETYPE]
GO
IF  EXISTS (SELECT * FROM sys.types st JOIN sys.schemas ss ON st.schema_id = ss.schema_id WHERE st.name = N'HBS_COUNTRY_TABLETYPE' AND ss.name = N'dbo')
DROP TYPE [dbo].[HBS_COUNTRY_TABLETYPE]
GO
IF  EXISTS (SELECT * FROM sys.types st JOIN sys.schemas ss ON st.schema_id = ss.schema_id WHERE st.name = N'HBS_FLIGHT_TABLETYPE' AND ss.name = N'dbo')
DROP TYPE [dbo].[HBS_FLIGHT_TABLETYPE]
GO
IF  EXISTS (SELECT * FROM sys.types st JOIN sys.schemas ss ON st.schema_id = ss.schema_id WHERE st.name = N'HBS_PASSENGER_TABLETYPE' AND ss.name = N'dbo')
DROP TYPE [dbo].[HBS_PASSENGER_TABLETYPE]
GO
IF  EXISTS (SELECT * FROM sys.types st JOIN sys.schemas ss ON st.schema_id = ss.schema_id WHERE st.name = N'HBS_POLICY_MANAGEMENT_TABLETYPE' AND ss.name = N'dbo')
DROP TYPE [dbo].[HBS_POLICY_MANAGEMENT_TABLETYPE]
GO
IF  EXISTS (SELECT * FROM sys.types st JOIN sys.schemas ss ON st.schema_id = ss.schema_id WHERE st.name = N'HBS_SCHEDULE_TABLETYPE' AND ss.name = N'dbo')
DROP TYPE [dbo].[HBS_SCHEDULE_TABLETYPE]
GO
IF  EXISTS (SELECT * FROM sys.types st JOIN sys.schemas ss ON st.schema_id = ss.schema_id WHERE st.name = N'HBS_TAG_TYPE_TABLETYPE' AND ss.name = N'dbo')
DROP TYPE [dbo].[HBS_TAG_TYPE_TABLETYPE]
GO
IF  EXISTS (SELECT * FROM sys.types st JOIN sys.schemas ss ON st.schema_id = ss.schema_id WHERE st.name = N'PSEUDO_BSM_TABLETYPE' AND ss.name = N'dbo')
DROP TYPE [dbo].[PSEUDO_BSM_TABLETYPE]
GO
IF  EXISTS (SELECT * FROM sys.types st JOIN sys.schemas ss ON st.schema_id = ss.schema_id WHERE st.name = N'ROUTING_TABLE_TABLETYPE' AND ss.name = N'dbo')
DROP TYPE [dbo].[ROUTING_TABLE_TABLETYPE]
GO
IF  EXISTS (SELECT * FROM sys.types st JOIN sys.schemas ss ON st.schema_id = ss.schema_id WHERE st.name = N'SORTATION_REASON_TABLETYPE' AND ss.name = N'dbo')
DROP TYPE [dbo].[SORTATION_REASON_TABLETYPE]
GO
IF  EXISTS (SELECT * FROM sys.types st JOIN sys.schemas ss ON st.schema_id = ss.schema_id WHERE st.name = N'SPECIAL_SECURITY_TAG_DESTINATION_MAPPING_TABLETYPE' AND ss.name = N'dbo')
DROP TYPE [dbo].[SPECIAL_SECURITY_TAG_DESTINATION_MAPPING_TABLETYPE]
GO
IF  EXISTS (SELECT * FROM sys.types st JOIN sys.schemas ss ON st.schema_id = ss.schema_id WHERE st.name = N'SYS_CONFIG_TABLETYPE' AND ss.name = N'dbo')
DROP TYPE [dbo].[SYS_CONFIG_TABLETYPE]
GO
IF  EXISTS (SELECT * FROM sys.types st JOIN sys.schemas ss ON st.schema_id = ss.schema_id WHERE st.name = N'TTS_MES_PRIORITY_TABLETYPE' AND ss.name = N'dbo')
DROP TYPE [dbo].[TTS_MES_PRIORITY_TABLETYPE]
GO
IF  EXISTS (SELECT * FROM sys.types st JOIN sys.schemas ss ON st.schema_id = ss.schema_id WHERE st.name = N'MAKEUP_FLIGHT_TYPE_MAPPING_TABLETYPE' AND ss.name = N'dbo')
DROP TYPE [dbo].[MAKEUP_FLIGHT_TYPE_MAPPING_TABLETYPE]
GO

USE [BHS_LOCALMES]
GO
/****** Object:  UserDefinedTableType [dbo].[AIRLINE_CODE_SHORTCUTS_TABLETYPE]    Script Date: 12/09/2010 15:38:37 ******/
CREATE TYPE [dbo].[AIRLINE_CODE_SHORTCUTS_TABLETYPE] AS TABLE(
	[ID] [varchar](15) NULL,
	[AIRLINE] [varchar](3) NULL,
	[DESCRIPTION] [nvarchar](100) NULL,
	[SYS_ACTION] [varchar](50) NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[AIRLINES_TABLETYPE]    Script Date: 12/09/2010 15:38:37 ******/
CREATE TYPE [dbo].[AIRLINES_TABLETYPE] AS TABLE(
	[CODE_IATA] [varchar](3) NULL,
	[CODE_ICAO] [varchar](3) NULL,
	[NAME] [nvarchar](50) NULL,
	[TICKETING_CODE] [varchar](4) NULL,
	[DESTINATION] [varchar](10) NULL,
	[DESTINATION1] [varchar](10) NULL,
	[RUSH] [varchar](10) NULL,
	[HANDLER] [varchar](3) NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[AIRPORTS_TABLETYPE]    Script Date: 12/09/2010 15:38:37 ******/
CREATE TYPE [dbo].[AIRPORTS_TABLETYPE] AS TABLE(
	[CODE_IATA] [varchar](3) NULL,
	[CODE_ICAO] [varchar](4) NULL,
	[NAME] [nvarchar](50) NULL,
	[COUNTRY] [nvarchar](50) NULL,
	[CITY] [nvarchar](30) NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[BAG_INFO_TABLETYPE]    Script Date: 12/09/2010 15:38:37 ******/
CREATE TYPE [dbo].[BAG_INFO_TABLETYPE] AS TABLE(
	[TIME_STAMP] [datetime] NULL,
	[INDEX_NO] [varchar](10) NULL,
	[GID] [varchar](10) NULL,
	[LICENSE_PLATE] [varchar](10) NULL,
	[LICENSE_PLATE1] [varchar](10) NULL,
	[LICENSE_PLATE2] [varchar](10) NULL,
	[LICENSE_PLATE3] [varchar](10) NULL,
	[MIN_SECURITY_LEVEL] [varchar](1) NULL,
	[CURRENT_HBS_LEVEL] [varchar](1) NULL,
	[HBS1_RESULT] [varchar](1) NULL,
	[HBS2_RESULT] [varchar](1) NULL,
	[HBS3_RESULT] [varchar](1) NULL,
	[HBS4_RESULT] [varchar](1) NULL,
	[HBS5_RESULT] [varchar](1) NULL,
	[CUSTOMS_RESULT] [varchar](1) NULL,
	[SORT_REASON] [varchar](2) NULL,
	[DEST1] [varchar](20) NULL,
	[DEST2] [varchar](20) NULL,
	[DEST3] [varchar](20) NULL,
	[RECYLE_COUNT] [int] NULL,
	[LAST_LOCATION] [varchar](20) NULL,
	[ENCODED_TYPE] [varchar](2) NULL,
	[OOG] [bit] NULL,
	[EBS] [bit] NULL,
	[DISCHARGED] [bit] NULL,
	[DISAPPEARED] [bit] NULL,
	[SORTED] [bit] NULL,
	[CREATED_BY] [varchar](15) NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[BAG_SORTING_TABLETYPE]    Script Date: 12/09/2010 15:38:37 ******/
CREATE TYPE [dbo].[BAG_SORTING_TABLETYPE] AS TABLE(
	[ID] [bigint] NULL,
	[DATA_ID] [bigint] NULL,
	[TIME_STAMP] [datetime] NULL,
	[DICTIONARY_VERSION] [int] NULL,
	[SOURCE] [varchar](1) NULL,
	[AIRPORT_CODE] [varchar](5) NULL,
	[LICENSE_PLATE] [varchar](10) NULL,
	[AIRLINE] [varchar](3) NULL,
	[FLIGHT_NUMBER] [varchar](5) NULL,
	[SDO] [datetime] NULL,
	[DESTINATION] [varchar](5) NULL,
	[TRAVEL_CLASS] [varchar](1) NULL,
	[INBOUND_AIRLINE] [varchar](3) NULL,
	[INBOUND_FLIGHT_NUMBER] [varchar](5) NULL,
	[INBOUND_SDO] [datetime] NULL,
	[INBOUND_AIRPORT_CODE] [varchar](5) NULL,
	[INBOUND_TRAVEL_CLASS] [varchar](1) NULL,
	[ONWARD_AIRLINE1] [varchar](3) NULL,
	[ONWARD_FLIGHT_NUMBER1] [varchar](5) NULL,
	[ONWARD_SDO1] [datetime] NULL,
	[ONWARD_AIRPORT_CODE1] [varchar](5) NULL,
	[ONWARD_TRAVEL_CLASS1] [varchar](1) NULL,
	[ONWARD_AIRLINE2] [varchar](3) NULL,
	[ONWARD_FLIGHT_NUMBER2] [varchar](5) NULL,
	[ONWARD_SDO2] [datetime] NULL,
	[ONWARD_AIRPORT_CODE2] [varchar](5) NULL,
	[ONWARD_TRAVEL_CLASS2] [varchar](1) NULL,
	[ONWARD_AIRLINE3] [varchar](3) NULL,
	[ONWARD_FLIGHT_NUMBER3] [varchar](5) NULL,
	[ONWARD_SDO3] [datetime] NULL,
	[ONWARD_AIRPORT_CODE3] [varchar](5) NULL,
	[ONWARD_TRAVEL_CLASS3] [varchar](1) NULL,
	[ONWARD_AIRLINE4] [varchar](3) NULL,
	[ONWARD_FLIGHT_NUMBER4] [varchar](5) NULL,
	[ONWARD_SDO4] [datetime] NULL,
	[ONWARD_AIRPORT_CODE4] [varchar](5) NULL,
	[ONWARD_TRAVEL_CLASS4] [varchar](5) NULL,
	[ONWARD_AIRLINE5] [varchar](3) NULL,
	[ONWARD_FLIGHT_NUMBER5] [varchar](5) NULL,
	[ONWARD_SDO5] [datetime] NULL,
	[ONWARD_AIRPORT_CODE5] [varchar](5) NULL,
	[ONWARD_TRAVEL_CLASS5] [varchar](1) NULL,
	[NO_PASSENGER_SAME_SURNAME] [int] NULL,
	[SURNAME] [nvarchar](30) NULL,
	[GIVEN_NAME] [nvarchar](30) NULL,
	[OTHERS_NAME] [nvarchar](100) NULL,
	[BAG_EXCEPTION] [varchar](10) NULL,
	[CHECK_IN_COUNTER] [varchar](10) NULL,
	[CHECK_IN_COUNTER_DESCRIPTION] [varchar](20) NULL,
	[CHECK_IN_TIME_STAMP] [datetime] NULL,
	[CHECK_IN_CARRIAGE_MEDIUM] [varchar](5) NULL,
	[CHECK_IN_TRANSPORT_ID] [varchar](20) NULL,
	[TAG_PRINTER_ID] [varchar](10) NULL,
	[RECONCILIATION_LOAD_AUTHORITY] [varchar](1) NULL,
	[RECONCILIATION_SEAT_NUMBER] [varchar](5) NULL,
	[RECONCILIATION_PASSENGER_STATUS] [varchar](1) NULL,
	[RECONCILIATION_SEQUENCE_NUMBER] [varchar](3) NULL,
	[RECONCILIATION_SECURITY_NUMBER] [varchar](3) NULL,
	[RECONCILIATION_PASSENGER_PROFILES_STATUS] [varchar](1) NULL,
	[RECONCILIATION_TRANSPORT_AUTHORITY] [varchar](1) NULL,
	[RECONCILIATION_BAG_TAG_STATUS] [varchar](1) NULL,
	[HANDLING_TERMINAL] [varchar](10) NULL,
	[HANDLING_BAR] [varchar](10) NULL,
	[HANDLING_GATE] [varchar](10) NULL,
	[WEIGHT_INDICATOR] [varchar](1) NULL,
	[WEIGHT_CHECKED_BAG_NUMBER] [int] NULL,
	[CHECKED_WEIGHT] [int] NULL,
	[UNCHECKED_WEIGHT] [int] NULL,
	[WEIGHT_UNIT] [varchar](2) NULL,
	[WEIGHT_LENGTH] [int] NULL,
	[WEIGHT_WIDTH] [int] NULL,
	[WEIGHT_HEIGHT] [int] NULL,
	[WEIGHT_BAG_TYPE_CODE] [varchar](10) NULL,
	[GROUND_TRANSPORT_EARLIEST_DELIVERY] [datetime] NULL,
	[GROUND_TRANSPORT_LATEST_DELIVERY] [datetime] NULL,
	[GROUND_TRANSPORT_DESCRIPTION] [varchar](200) NULL,
	[FREQUENT_TRAVELLER_ID_NUMBER] [varchar](25) NULL,
	[FREQUENT_TRAVELLER_TIER_ID] [varchar](25) NULL,
	[CORPORATE_NAME] [varchar](20) NULL,
	[AUTOMATED_PNR_ADDRESS] [varchar](20) NULL,
	[MESSAGE_PRINTER_ID] [varchar](10) NULL,
	[INTERNAL_AIRLINE_DATA] [varchar](60) NULL,
	[SECURITY_SCREENING_INSTRUCTION] [varchar](3) NULL,
	[SECURITY_SCREENING_RESULT] [varchar](3) NULL,
	[SECURITY_SCREENING_RESULT_REASON] [varchar](1) NULL,
	[SECURITY_SCREENING_RESULT_METHOD] [varchar](5) NULL,
	[SECURITY_SCREENING_AUTOGRAPH] [varchar](10) NULL,
	[SECURITY_SCREENING_FREE_TEXT] [varchar](40) NULL,
	[HIGH_RISK] [char](1) NULL,
	[HBS_LEVEL_REQUIRED] [char](1) NULL,
	[CREATED_BY] [varchar](15) NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[CHUTE_MAPPING_TABLETYPE]    Script Date: 12/09/2010 15:38:37 ******/
CREATE TYPE [dbo].[CHUTE_MAPPING_TABLETYPE] AS TABLE(
	[CHUTE] [varchar](20) NULL,
	[TTS_ID] [varchar](20) NULL,
	[SORTER] [varchar](10) NULL,
	[DESTINATION] [varchar](20) NULL,
	[IS_AVAILABLE] [bit] NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[DESTINATIONS_TABLETYPE]    Script Date: 12/09/2010 15:38:37 ******/
CREATE TYPE [dbo].[DESTINATIONS_TABLETYPE] AS TABLE(
	[DESTINATION] [varchar](10) NULL,
	[SUBSYSTEM] [varchar](10) NULL,
	[DESCRIPTION] [nvarchar](100) NULL,
	[IS_AVAILABLE] [bit] NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[FALLBACK_MAPPING_TABLETYPE]    Script Date: 12/09/2010 15:38:37 ******/
CREATE TYPE [dbo].[FALLBACK_MAPPING_TABLETYPE] AS TABLE(
	[ID] [varchar](2) NULL,
	[DESTINATION] [varchar](10) NULL,
	[DESCRIPTION] [nvarchar](100) NULL,
	[SYS_ACTION] [varchar](50) NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[FALLBACK_TAG_INFO_TABLETYPE]    Script Date: 12/09/2010 15:38:37 ******/
CREATE TYPE [dbo].[FALLBACK_TAG_INFO_TABLETYPE] AS TABLE(
	[ID] [bigint] NULL,
	[TIME_STAMP] [datetime] NULL,
	[NO_OF_FALLBACK] [varchar](2) NULL,
	[FALLBACK_NO_1] [varchar](2) NULL,
	[DESTINATION_1A] [varchar](4) NULL,
	[DESTINATION_1B] [varchar](4) NULL,
	[FLIGHT_TYPE_1] [varchar](1) NULL,
	[FALLBACK_NO_2] [varchar](2) NULL,
	[DESTINATION_2A] [varchar](4) NULL,
	[DESTINATION_2B] [varchar](4) NULL,
	[FLIGHT_TYPE_2] [varchar](1) NULL,
	[FALLBACK_NO_3] [varchar](2) NULL,
	[DESTINATION_3A] [varchar](4) NULL,
	[DESTINATION_3B] [varchar](4) NULL,
	[FLIGHT_TYPE_3] [varchar](1) NULL,
	[FALLBACK_NO_4] [varchar](2) NULL,
	[DESTINATION_4A] [varchar](4) NULL,
	[DESTINATION_4B] [varchar](4) NULL,
	[FLIGHT_TYPE_4] [varchar](1) NULL,
	[FALLBACK_NO_5] [varchar](2) NULL,
	[DESTINATION_5A] [varchar](4) NULL,
	[DESTINATION_5B] [varchar](4) NULL,
	[FLIGHT_TYPE_5] [varchar](1) NULL,
	[FALLBACK_NO_6] [varchar](2) NULL,
	[DESTINATION_6A] [varchar](4) NULL,
	[DESTINATION_6B] [varchar](4) NULL,
	[FLIGHT_TYPE_6] [varchar](1) NULL,
	[FALLBACK_NO_7] [varchar](2) NULL,
	[DESTINATION_7A] [varchar](4) NULL,
	[DESTINATION_7B] [varchar](4) NULL,
	[FLIGHT_TYPE_7] [varchar](1) NULL,
	[FALLBACK_NO_8] [varchar](2) NULL,
	[DESTINATION_8A] [varchar](4) NULL,
	[DESTINATION_8B] [varchar](4) NULL,
	[FLIGHT_TYPE_8] [varchar](1) NULL,
	[FALLBACK_NO_9] [varchar](2) NULL,
	[DESTINATION_9A] [varchar](4) NULL,
	[DESTINATION_9B] [varchar](4) NULL,
	[FLIGHT_TYPE_9] [varchar](1) NULL,
	[FALLBACK_NO_10] [varchar](2) NULL,
	[DESTINATION_10A] [varchar](4) NULL,
	[DESTINATION_10B] [varchar](4) NULL,
	[FLIGHT_TYPE_10] [varchar](1) NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[FLIGHT_PLAN_ALLOC_TABLETYPE]    Script Date: 12/09/2010 15:38:37 ******/
CREATE TYPE [dbo].[FLIGHT_PLAN_ALLOC_TABLETYPE] AS TABLE(
	[ID] [bigint] NULL,
	[AIRLINE] [varchar](3) NULL,
	[FLIGHT_NUMBER] [varchar](5) NULL,
	[SDO] [datetime] NULL,
	[STO] [varchar](4) NULL,
	[RESOURCE] [varchar](10) NULL,
	[WEEKDAY] [char](1) NULL,
	[EDO] [datetime] NULL,
	[ETO] [varchar](4) NULL,
	[ADO] [datetime] NULL,
	[ATO] [varchar](4) NULL,
	[IDO] [datetime] NULL,
	[ITO] [varchar](4) NULL,
	[TRAVEL_CLASS] [varchar](1) NULL,
	[FLIGHT_DESTINATION] [varchar](3) NULL,
	[BAG_TYPE] [varchar](10) NULL,
	[TRANSFER] [varchar](10) NULL,
	[COMMENT_ID] [bigint] NULL,
	[HIGH_RISK] [char](1) NULL,
	[HBS_LEVEL_REQUIRED] [char](1) NULL,
	[EARLY_OPEN_OFFSET] [varchar](5) NULL,
	[EARLY_OPEN_ENABLED] [bit] NULL,
	[ALLOC_OPEN_OFFSET] [varchar](5) NULL,
	[ALLOC_OPEN_RELATED] [varchar](4) NULL,
	[ALLOC_CLOSE_OFFSET] [varchar](5) NULL,
	[ALLOC_CLOSE_RELATED] [varchar](4) NULL,
	[RUSH_DURATION] [varchar](5) NULL,
	[SCHEME_TYPE] [varchar](2) NULL,
	[CREATED_BY] [varchar](15) NULL,
	[TIME_STAMP] [datetime] NULL,
	[HOUR] [varchar](2) NULL,
	[IS_MANUAL_CLOSE] [bit] NULL,
	[IS_CLOSED] [bit] NULL,
	[IS_MISS_TEMPLATE_FLIGHT] [bit] NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[FLIGHT_PLAN_SORTING_TABLETYPE]    Script Date: 12/09/2010 15:38:38 ******/
CREATE TYPE [dbo].[FLIGHT_PLAN_SORTING_TABLETYPE] AS TABLE(
	[TIME_STAMP] [datetime] NULL,
	[DATA_ID] [bigint] NULL,
	[AIRLINE] [varchar](3) NULL,
	[FLIGHT_NUMBER] [varchar](5) NULL,
	[FLIGHT_NUMBER_SUFFIX] [varchar](3) NULL,
	[HANDLER] [varchar](20) NULL,
	[SDO] [datetime] NULL,
	[STO] [varchar](4) NULL,
	[EDO] [datetime] NULL,
	[ETO] [varchar](4) NULL,
	[ADO] [datetime] NULL,
	[ATO] [varchar](4) NULL,
	[IDO] [datetime] NULL,
	[ITO] [varchar](4) NULL,
	[BLOCK_OFF_TIME] [varchar](14) NULL,
	[FINAL_DEST] [varchar](3) NULL,
	[DEST1] [varchar](3) NULL,
	[DEST2] [varchar](3) NULL,
	[DEST3] [varchar](3) NULL,
	[DEST4] [varchar](3) NULL,
	[DEST5] [varchar](3) NULL,
	[CANCELLED] [varchar](1) NULL,
	[AIRCRAFT_TYPE] [varchar](4) NULL,
	[HANDLER_SPECIFIC_DESC] [varchar](12) NULL,
	[AIRCRAFT_VERSION] [varchar](12) NULL,
	[TERMINAL] [varchar](5) NULL,
	[CHECKIN_AREA] [varchar](10) NULL,
	[CHECKIN_STATUS] [varchar](10) NULL,
	[PUBLIC_REMARK_CODE] [varchar](10) NULL,
	[PIER] [varchar](5) NULL,
	[GATE] [varchar](5) NULL,
	[PARKING_STAND] [varchar](5) NULL,
	[NATURE] [varchar](15) NULL,
	[SORTING_DEST1] [varchar](10) NULL,
	[SORTING_DEST2] [varchar](10) NULL,
	[GENERAL_PURPOSE] [varchar](40) NULL,
	[FI_EXCEPTION] [varchar](10) NULL,
	[MASTER_AIRLINE] [varchar](3) NULL,
	[MASTER_FLIGHT_NUMBER] [varchar](5) NULL,
	[MASTER_FLIGHT_NUMBER_SUFFIX] [varchar](3) NULL,
	[MASTER_SDO] [varchar](8) NULL,
	[BOOKED_PAX] [varchar](20) NULL,
	[HBS_LEVEL_REQUIRED] [char](1) NULL,
	[WEEKDAY] [varchar](1) NULL,
	[HOUR] [varchar](10) NULL,
	[HIGH_RISK] [varchar](1) NULL,
	[ALLOC_OPEN_TIME] [datetime] NULL,
	[ALLOC_CLOSE_TIME] [datetime] NULL,
	[CREATED_BY] [varchar](15) NULL,
	[IS_ALLOCATED] [bit] NULL,
	[CUSTOMS_REQUIRED] [bit] NULL,
	[FLIGHT_TYPE] [varchar](1) NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[FOUR_DIGITS_FALLBACK_MAPPING_TABLETYPE]    Script Date: 12/09/2010 15:38:38 ******/
CREATE TYPE [dbo].[FOUR_DIGITS_FALLBACK_MAPPING_TABLETYPE] AS TABLE(
	[ID] [varchar](4) NULL,
	[DESTINATION] [varchar](10) NULL,
	[DESCRIPTION] [nvarchar](100) NULL,
	[SYS_ACTION] [varchar](50) NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[FUNCTION_ALLOC_GANTT_TABLETYPE]    Script Date: 12/09/2010 15:38:38 ******/
CREATE TYPE [dbo].[FUNCTION_ALLOC_GANTT_TABLETYPE] AS TABLE(
	[ID] [bigint] NULL,
	[TIME_STAMP] [datetime] NULL,
	[FUNCTION_TYPE] [varchar](4) NULL,
	[RESOURCE] [varchar](10) NULL,
	[ALLOC_OPEN_DATETIME] [datetime] NULL,
	[ALLOC_CLOSE_DATETIME] [datetime] NULL,
	[IS_CLOSED] [bit] NULL,
	[EXCEPTION] [varchar](10) NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[FUNCTION_ALLOC_LIST_TABLETYPE]    Script Date: 12/09/2010 15:38:38 ******/
CREATE TYPE [dbo].[FUNCTION_ALLOC_LIST_TABLETYPE] AS TABLE(
	[ID] [bigint] NULL,
	[TIME_STAMP] [datetime] NULL,
	[FUNCTION_TYPE] [varchar](4) NULL,
	[RESOURCE] [varchar](10) NULL,
	[IS_ENABLED] [bit] NULL,
	[SYS_TAB_NAME] [varchar](20) NULL,
	[SYS_ACTION] [varchar](50) NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[FUNCTION_TYPES_TABLETYPE]    Script Date: 12/09/2010 15:38:38 ******/
CREATE TYPE [dbo].[FUNCTION_TYPES_TABLETYPE] AS TABLE(
	[TYPE] [varchar](4) NULL,
	[GROUP] [varchar](5) NULL,
	[DESCRIPTION] [nvarchar](100) NULL,
	[IS_ALLOCATED] [bit] NULL,
	[IS_ENABLED] [bit] NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[HBS_AIRLINE_TABLETYPE]    Script Date: 12/09/2010 15:38:38 ******/
CREATE TYPE [dbo].[HBS_AIRLINE_TABLETYPE] AS TABLE(
	[ID] [varchar](3) NULL,
	[LEVEL] [varchar](1) NULL,
	[DESCRIPTION] [nvarchar](100) NULL,
	[SYS_ACTION] [varchar](50) NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[HBS_COUNTRY_TABLETYPE]    Script Date: 12/09/2010 15:38:38 ******/
CREATE TYPE [dbo].[HBS_COUNTRY_TABLETYPE] AS TABLE(
	[ID] [nvarchar](50) NULL,
	[LEVEL] [varchar](1) NULL,
	[DESCRIPTION] [nvarchar](100) NULL,
	[SYS_ACTION] [varchar](50) NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[HBS_FLIGHT_TABLETYPE]    Script Date: 12/09/2010 15:38:38 ******/
CREATE TYPE [dbo].[HBS_FLIGHT_TABLETYPE] AS TABLE(
	[ID] [varchar](10) NULL,
	[LEVEL] [varchar](1) NULL,
	[DESCRIPTION] [nvarchar](100) NULL,
	[SYS_ACTION] [varchar](50) NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[HBS_PASSENGER_TABLETYPE]    Script Date: 12/09/2010 15:38:38 ******/
CREATE TYPE [dbo].[HBS_PASSENGER_TABLETYPE] AS TABLE(
	[ID] [bigint] NULL,
	[SURNAME] [nvarchar](30) NULL,
	[GIVEN_NAME] [nvarchar](30) NULL,
	[ADDITIONAL_GIVEN_NAME] [nvarchar](100) NULL,
	[LEVEL] [varchar](1) NULL,
	[DESCRIPTION] [nvarchar](100) NULL,
	[SYS_ACTION] [varchar](50) NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[HBS_POLICY_MANAGEMENT_TABLETYPE]    Script Date: 12/09/2010 15:38:38 ******/
CREATE TYPE [dbo].[HBS_POLICY_MANAGEMENT_TABLETYPE] AS TABLE(
	[ID] [bigint] NULL,
	[HBS_TAG] [varchar](10) NULL,
	[ENABLED] [bit] NULL,
	[TYPE] [varchar](10) NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[HBS_SCHEDULE_TABLETYPE]    Script Date: 12/09/2010 15:38:38 ******/
CREATE TYPE [dbo].[HBS_SCHEDULE_TABLETYPE] AS TABLE(
	[ID] [bigint] NULL,
	[START_TIME] [datetime] NULL,
	[END_TIME] [datetime] NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[HBS_TAG_TYPE_TABLETYPE]    Script Date: 12/09/2010 15:38:38 ******/
CREATE TYPE [dbo].[HBS_TAG_TYPE_TABLETYPE] AS TABLE(
	[ID] [varchar](10) NULL,
	[DESCRIPTION] [varchar](50) NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[PSEUDO_BSM_TABLETYPE]    Script Date: 12/09/2010 15:38:38 ******/
CREATE TYPE [dbo].[PSEUDO_BSM_TABLETYPE] AS TABLE(
	[TIME_STAMP] [datetime] NULL,
	[LICENSE_PLATE] [varchar](10) NULL,
	[AIRLINE] [varchar](3) NULL,
	[FLIGHT_NUMBER] [varchar](5) NULL,
	[SDO] [datetime] NULL,
	[DESCRITION] [varchar](50) NULL,
	[TYPE] [varchar](10) NULL,
	[CREATED_BY] [varchar](15) NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[ROUTING_TABLE_TABLETYPE]    Script Date: 12/09/2010 15:38:38 ******/
CREATE TYPE [dbo].[ROUTING_TABLE_TABLETYPE] AS TABLE(
	[SUBSYSTEM] [varchar](10) NULL,
	[LOCATION] [varchar](20) NULL,
	[DESCRIPTION] [nvarchar](50) NULL,
	[COST] [decimal](18, 0) NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[SORTATION_REASON_TABLETYPE]    Script Date: 12/09/2010 15:38:38 ******/
CREATE TYPE [dbo].[SORTATION_REASON_TABLETYPE] AS TABLE(
	[REASON] [varchar](2) NULL,
	[DESCRIPTION] [nvarchar](50) NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[SPECIAL_SECURITY_TAG_DESTINATION_MAPPING_TABLETYPE]    Script Date: 12/09/2010 15:38:38 ******/
CREATE TYPE [dbo].[SPECIAL_SECURITY_TAG_DESTINATION_MAPPING_TABLETYPE] AS TABLE(
	[ID] [varchar](2) NULL,
	[DESTINATION] [varchar](10) NULL,
	[DESCRIPTION] [nvarchar](100) NULL,
	[SYS_ACTION] [varchar](50) NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[SYS_CONFIG_TABLETYPE]    Script Date: 12/09/2010 15:38:38 ******/
CREATE TYPE [dbo].[SYS_CONFIG_TABLETYPE] AS TABLE(
	[SYS_KEY] [varchar](40) NULL,
	[SYS_VALUE] [varchar](20) NULL,
	[DEFAULT_VALUE] [varchar](20) NULL,
	[LAST_VALUE] [varchar](20) NULL,
	[DESCRIPTION] [nvarchar](80) NULL,
	[VALUE_TOKEN] [varchar](80) NULL,
	[SYS_ACTION] [varchar](50) NULL,
	[GROUP_NAME] [varchar](20) NULL,
	[ORDER_FLAG] [varchar](1) NULL,
	[IS_ENABLED] [bit] NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[TTS_MES_PRIORITY_TABLETYPE]    Script Date: 12/09/2010 15:38:38 ******/
CREATE TYPE [dbo].[TTS_MES_PRIORITY_TABLETYPE] AS TABLE(
	[SYS_KEY] [varchar](40) NULL,
	[VALUE] [varchar](15) NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[MAKEUP_FLIGHT_TYPE_MAPPING_TABLETYPE]    Script Date: 01/19/2011 11:58:58 ******/
CREATE TYPE [dbo].[MAKEUP_FLIGHT_TYPE_MAPPING_TABLETYPE] AS TABLE(
	[ID] [bigint] NULL,
	[RESOURCE] [varchar](10) NULL,
	[FLIGHT_TYPE] [varchar](1) NULL
)
GO

PRINT 'INFO: .'
PRINT 'INFO: .'
PRINT 'INFO: .'
GO
PRINT 'INFO: End of STEP2.1'
GO