sqlcmd -U sa -P DBAdm1n@BHS.irel -d BHSDB_CLT -i ./stp_MES_ClearLocalData.sql
sqlcmd -U sa -P DBAdm1n@BHS.irel -d BHSDB_CLT -i ./stp_MES_GETLOCALINSERTEDDATA.sql
sqlcmd -U sa -P DBAdm1n@BHS.irel -d BHSDB_CLT -i ./stp_MES_GETREQUIREDDATATOLOCAL.sql
sqlcmd -U sa -P DBAdm1n@BHS.irel -d BHSDB_CLT -i ./stp_MES_INSERT_4DIGITSFALLBACKMAPPING.sql
sqlcmd -U sa -P DBAdm1n@BHS.irel -d BHSDB_CLT -i ./stp_MES_INSERT_AIRLINES.sql
sqlcmd -U sa -P DBAdm1n@BHS.irel -d BHSDB_CLT -i ./stp_MES_INSERT_AIRPORTS.sql
sqlcmd -U sa -P DBAdm1n@BHS.irel -d BHSDB_CLT -i ./stp_MES_INSERT_BAGINFO.sql
sqlcmd -U sa -P DBAdm1n@BHS.irel -d BHSDB_CLT -i ./stp_MES_INSERT_BAGSORTING.sql
sqlcmd -U sa -P DBAdm1n@BHS.irel -d BHSDB_CLT -i ./stp_MES_INSERT_DESTINATIONS.sql
sqlcmd -U sa -P DBAdm1n@BHS.irel -d BHSDB_CLT -i ./stp_MES_INSERT_DESTINATION_CHUTE_MAPPING.sql
sqlcmd -U sa -P DBAdm1n@BHS.irel -d BHSDB_CLT -i ./stp_MES_INSERT_DESTINATION_PATH_MAPPING.sql
sqlcmd -U sa -P DBAdm1n@BHS.irel -d BHSDB_CLT -i ./stp_MES_INSERT_FALLBACKMAPPING.sql
sqlcmd -U sa -P DBAdm1n@BHS.irel -d BHSDB_CLT -i ./stp_MES_INSERT_FLIGHT_PLAN_ALLOC.sql
sqlcmd -U sa -P DBAdm1n@BHS.irel -d BHSDB_CLT -i ./stp_MES_INSERT_FLIGHT_PLAN_SORTING.sql
sqlcmd -U sa -P DBAdm1n@BHS.irel -d BHSDB_CLT -i ./stp_MES_INSERT_FUNCTION_ALLOC_GANTT.sql
sqlcmd -U sa -P DBAdm1n@BHS.irel -d BHSDB_CLT -i ./stp_MES_INSERT_FUNCTION_ALLOC_LIST.sql
sqlcmd -U sa -P DBAdm1n@BHS.irel -d BHSDB_CLT -i ./stp_MES_INSERT_FUNCTION_TYPES.sql
sqlcmd -U sa -P DBAdm1n@BHS.irel -d BHSDB_CLT -i ./stp_MES_INSERT_ITEM_ENCODED_FROM_LOCAL.sql
sqlcmd -U sa -P DBAdm1n@BHS.irel -d BHSDB_CLT -i ./stp_MES_INSERT_ITEM_READY_FROM_LOCAL.sql
sqlcmd -U sa -P DBAdm1n@BHS.irel -d BHSDB_CLT -i ./stp_MES_INSERT_ITEM_REMOVED_FROM_LOCAL.sql
sqlcmd -U sa -P DBAdm1n@BHS.irel -d BHSDB_CLT -i ./stp_MES_INSERT_LOCATIONS.sql
sqlcmd -U sa -P DBAdm1n@BHS.irel -d BHSDB_CLT -i ./stp_MES_INSERT_SECURITY_CATEGORIES.sql
sqlcmd -U sa -P DBAdm1n@BHS.irel -d BHSDB_CLT -i ./stp_MES_INSERT_SECURITY_GROUPS.sql
sqlcmd -U sa -P DBAdm1n@BHS.irel -d BHSDB_CLT -i ./stp_MES_INSERT_SECURITY_GROUP_TASK.sql
sqlcmd -U sa -P DBAdm1n@BHS.irel -d BHSDB_CLT -i ./stp_MES_INSERT_SECURITY_GROUP_TASK_MAPPING.sql
sqlcmd -U sa -P DBAdm1n@BHS.irel -d BHSDB_CLT -i ./stp_MES_INSERT_SECURITY_TASKS.sql
sqlcmd -U sa -P DBAdm1n@BHS.irel -d BHSDB_CLT -i ./stp_MES_INSERT_SECURITY_USERS.sql
sqlcmd -U sa -P DBAdm1n@BHS.irel -d BHSDB_CLT -i ./stp_MES_INSERT_SECURITY_USER_RIGHTS.sql
sqlcmd -U sa -P DBAdm1n@BHS.irel -d BHSDB_CLT -i ./stp_MES_INSERT_SORTATION_REASON.sql
sqlcmd -U sa -P DBAdm1n@BHS.irel -d BHSDB_CLT -i ./stp_MES_INSERT_SYS_CONFIG.sql
sqlcmd -U sa -P DBAdm1n@BHS.irel -d BHSDB_CLT -i ./stp_MES_REMOVELOCALINSERTEDDATA.sql
PAUSE