USE [BHSDB_CLT_LOCAL]
GO
/****** Object:  StoredProcedure [dbo].[stp_MES_INSERT_FUNCTION_ALLOC_GANTT]    Script Date: 02-04-2014 11:39:16 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[stp_MES_INSERT_SECURITY_CATEGORIES]
	@SECURITY_CATEGORIES_TABLETYPE SECURITY_CATEGORIES_TABLETYPE READONLY
AS
BEGIN
	SET NOCOUNT ON;
	DELETE FROM SECURITY_CATEGORIES;
	
    INSERT INTO SECURITY_CATEGORIES([SECU_CAT_CODE], [NAME], [IS_ACTIVE], [DESCRIPTION]) 
	SELECT [SECU_CAT_CODE], [NAME], [IS_ACTIVE], [DESCRIPTION] 
    FROM @SECURITY_CATEGORIES_TABLETYPE

END
