USE [BHSDB_CLT_LOCAL]
GO
/****** Object:  StoredProcedure [dbo].[stp_MES_INSERT_FUNCTION_ALLOC_GANTT]    Script Date: 02-04-2014 11:39:16 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[stp_MES_INSERT_DESTINATION_CHUTE_MAPPING]
	@DESTINATION_CHUTE_MAPPING_TABLETYPE DESTINATION_CHUTE_MAPPING_TABLETYPE READONLY
AS
BEGIN
	SET NOCOUNT ON;
	DELETE FROM DESTINATION_CHUTE_MAPPING;
	
    INSERT INTO DESTINATION_CHUTE_MAPPING( [DESTINATION], [SUBSYSTEM], [LOCATIONS], [STATUS], [RECIRCULATE], [LOCATION_ID]) 
	SELECT [DESTINATION], [SUBSYSTEM], [LOCATIONS], [STATUS], [RECIRCULATE], [LOCATION_ID] 
    FROM @DESTINATION_CHUTE_MAPPING_TABLETYPE

END
