//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGL.MESGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PGL.MESGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap BS {
            get {
                object obj = ResourceManager.GetObject("BS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BS1 {
            get {
                object obj = ResourceManager.GetObject("BS1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Computer {
            get {
                object obj = ResourceManager.GetObject("Computer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap down {
            get {
                object obj = ResourceManager.GetObject("down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap downdown {
            get {
                object obj = ResourceManager.GetObject("downdown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Icon Help3 {
            get {
                object obj = ResourceManager.GetObject("Help3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon Hnetwiz {
            get {
                object obj = ResourceManager.GetObject("Hnetwiz", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Bitmap left {
            get {
                object obj = ResourceManager.GetObject("left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap left1 {
            get {
                object obj = ResourceManager.GetObject("left1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap leftleft {
            get {
                object obj = ResourceManager.GetObject("leftleft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap leftleft1 {
            get {
                object obj = ResourceManager.GetObject("leftleft1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Icon Logout {
            get {
                object obj = ResourceManager.GetObject("Logout", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon Logout1 {
            get {
                object obj = ResourceManager.GetObject("Logout1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Bitmap osk {
            get {
                object obj = ResourceManager.GetObject("osk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Pals_CMYK {
            get {
                object obj = ResourceManager.GetObject("Pals CMYK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Pals_CMYK_Logo {
            get {
                object obj = ResourceManager.GetObject("Pals CMYK_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PGL_Graphic {
            get {
                object obj = ResourceManager.GetObject("PGL Graphic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap right {
            get {
                object obj = ResourceManager.GetObject("right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap right1 {
            get {
                object obj = ResourceManager.GetObject("right1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap rightright {
            get {
                object obj = ResourceManager.GetObject("rightright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap rightright1 {
            get {
                object obj = ResourceManager.GetObject("rightright1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode bag to airline rush destination.
        /// </summary>
        public static string sAirlineRush {
            get {
                return ResourceManager.GetString("sAirlineRush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string sAppMessageBoxTitleConfirm {
            get {
                return ResourceManager.GetString("sAppMessageBoxTitleConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string sAppMessageBoxTitleInfo {
            get {
                return ResourceManager.GetString("sAppMessageBoxTitleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string sAppMessageBoxWarning {
            get {
                return ResourceManager.GetString("sAppMessageBoxWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter IATA Airline Code.
        /// </summary>
        public static string sEnterAirlineCode {
            get {
                return ResourceManager.GetString("sEnterAirlineCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination not available.
        /// </summary>
        public static string sErrorDestinationNotAvailable {
            get {
                return ResourceManager.GetString("sErrorDestinationNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding fail.
        /// </summary>
        public static string sErrorEncodeFail {
            get {
                return ResourceManager.GetString("sErrorEncodeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to generate In-house BSM.
        /// </summary>
        public static string sErrorInhousePrintFail {
            get {
                return ResourceManager.GetString("sErrorInhousePrintFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to update In-house BSM.
        /// </summary>
        public static string sErrorInhouseUpdateFail {
            get {
                return ResourceManager.GetString("sErrorInhouseUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown airline code.
        /// </summary>
        public static string sErrorInvalidAirlineCode {
            get {
                return ResourceManager.GetString("sErrorInvalidAirlineCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid destination.
        /// </summary>
        public static string sErrorInvalidDestination {
            get {
                return ResourceManager.GetString("sErrorInvalidDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid first digit.
        /// </summary>
        public static string sErrorInvalidFirstDigit {
            get {
                return ResourceManager.GetString("sErrorInvalidFirstDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown flight.
        /// </summary>
        public static string sErrorInvalidFlight {
            get {
                return ResourceManager.GetString("sErrorInvalidFlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown format.
        /// </summary>
        public static string sErrorInvalidFormat {
            get {
                return ResourceManager.GetString("sErrorInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid quantity.
        /// </summary>
        public static string sErrorInvalidQuantity {
            get {
                return ResourceManager.GetString("sErrorInvalidQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Tag Number.
        /// </summary>
        public static string sErrorInvalidTagNumber {
            get {
                return ResourceManager.GetString("sErrorInvalidTagNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not found.
        /// </summary>
        public static string sErrorItemNotfound {
            get {
                return ResourceManager.GetString("sErrorItemNotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System fail to initialize.
        /// </summary>
        public static string sErrorLoadFail {
            get {
                return ResourceManager.GetString("sErrorLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to remove item.
        /// </summary>
        public static string sErrorRemoveFail {
            get {
                return ResourceManager.GetString("sErrorRemoveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find destination. Please use other encoding mode..
        /// </summary>
        public static string sErrorUnknownDest {
            get {
                return ResourceManager.GetString("sErrorUnknownDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rush set for airline! Bag encoded to global rush function allocation.
        /// </summary>
        public static string sFunctionRush {
            get {
                return ResourceManager.GetString("sFunctionRush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bag reach to MES more than .
        /// </summary>
        public static string sMessageBagReoccurance {
            get {
                return ResourceManager.GetString("sMessageBagReoccurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &quot;OK&quot; to confirm destination.
        /// </summary>
        public static string sMessageConfirm {
            get {
                return ResourceManager.GetString("sMessageConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &quot;OK&quot; to confirm destination and release bag.
        /// </summary>
        public static string sMessageConfirmRelease {
            get {
                return ResourceManager.GetString("sMessageConfirmRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key in flight code and press &quot;Enter&quot;.
        /// </summary>
        public static string sMessageEncodeByFlight {
            get {
                return ResourceManager.GetString("sMessageEncodeByFlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key in airline code  and press &quot;Enter&quot;.
        /// </summary>
        public static string sMessageEncodeByRushDestination {
            get {
                return ResourceManager.GetString("sMessageEncodeByRushDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key in destination code  and press &quot;Enter&quot;.
        /// </summary>
        public static string sMessageEncodeBySortDestination {
            get {
                return ResourceManager.GetString("sMessageEncodeBySortDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not encode a stray bag to sort destination.
        /// </summary>
        public static string sMessageEncodeBySortDestinationFail {
            get {
                return ResourceManager.GetString("sMessageEncodeBySortDestinationFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key in IATA number  and press &quot;Enter&quot;.
        /// </summary>
        public static string sMessageEncodeByTag {
            get {
                return ResourceManager.GetString("sMessageEncodeByTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding successfully.
        /// </summary>
        public static string sMessageEncodeSuccess {
            get {
                return ResourceManager.GetString("sMessageEncodeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready for encode.
        /// </summary>
        public static string sMessageItemReady {
            get {
                return ResourceManager.GetString("sMessageItemReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MES can not decide the destination automatically because multiple BSM received.
        /// </summary>
        public static string sMessageMultiBSMforMES {
            get {
                return ResourceManager.GetString("sMessageMultiBSMforMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &quot;Enter&quot; to confirm input data.
        /// </summary>
        public static string sMessagePressEnter {
            get {
                return ResourceManager.GetString("sMessagePressEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &quot;Dispatch&quot; to release bag.
        /// </summary>
        public static string sMessageRelease {
            get {
                return ResourceManager.GetString("sMessageRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not remove bag.
        /// </summary>
        public static string sMessageRemoveFail {
            get {
                return ResourceManager.GetString("sMessageRemoveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bag has been returned .
        /// </summary>
        public static string sMessageReOccurance {
            get {
                return ResourceManager.GetString("sMessageReOccurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select destination.
        /// </summary>
        public static string sMessageSelect {
            get {
                return ResourceManager.GetString("sMessageSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode by Flight is not allowed for stray bag.
        /// </summary>
        public static string sMessageStrayBagForFlightMode {
            get {
                return ResourceManager.GetString("sMessageStrayBagForFlightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode by Rush is not allowed for stray bag.
        /// </summary>
        public static string sMessageStrayBagForRushMode {
            get {
                return ResourceManager.GetString("sMessageStrayBagForRushMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallback Tag successfully printed.
        /// </summary>
        public static string sMessageSuccessFallbakPrint {
            get {
                return ResourceManager.GetString("sMessageSuccessFallbakPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IATA Tag successfully printed.
        /// </summary>
        public static string sMessageSuccessIATAPrint {
            get {
                return ResourceManager.GetString("sMessageSuccessIATAPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-House Tag successfully printed.
        /// </summary>
        public static string sMessageSuccessInhousePrint {
            get {
                return ResourceManager.GetString("sMessageSuccessInhousePrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item successfully removed.
        /// </summary>
        public static string sMessageSuccessRemove {
            get {
                return ResourceManager.GetString("sMessageSuccessRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete selected In-house BSM?.
        /// </summary>
        public static string sQuestionDeleteIHTag {
            get {
                return ResourceManager.GetString("sQuestionDeleteIHTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to update changes?.
        /// </summary>
        public static string sQuestionUpdateIHTag {
            get {
                return ResourceManager.GetString("sQuestionUpdateIHTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26 November, 2010.
        /// </summary>
        public static string sReleaseDate {
            get {
                return ResourceManager.GetString("sReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bag is not clear HBS, but EDS is unavailable. Remove the bag or send it to problem discharge..
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        public static System.Drawing.Icon Switch {
            get {
                object obj = ResourceManager.GetObject("Switch", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIV.
        /// </summary>
        public static string sWorkingMode {
            get {
                return ResourceManager.GetString("sWorkingMode", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap up {
            get {
                object obj = ResourceManager.GetObject("up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap UpArrow {
            get {
                object obj = ResourceManager.GetObject("UpArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap upup {
            get {
                object obj = ResourceManager.GetObject("upup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap User1 {
            get {
                object obj = ResourceManager.GetObject("User1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
