SELECT * FROM FLIGHT_PLAN_ALLOC;
SELECT * FROM FLIGHT_PLAN_SORTING;
SELECT * FROM BAG_SORTING;
SELECT * FROM ALLOC_RESOURCES;
SELECT * FROM FUNCTION_ALLOC_LIST;

SELECT * FROM LOCATIONS WHERE LOCATION LIKE 'MU%';
SELECT * FROM DESTINATIONS;

--1. INSERT INTO ALLOCATION RESOURCE

INSERT INTO ALLOC_RESOURCES VALUES(6,'MU7','MU7','Carousel Unit');

--2. UPDATE FLIGHT PLAN SDO

SELECT CAST(SUBSTRING(CAST(GETDATE() AS VARCHAR),1,10) AS DATETIME);

SELECT CONVERT(DATETIME,SUBSTRING(CONVERT(VARCHAR,GETDATE(),103),1,10),103);

DECLARE @TODAY DATETIME = CONVERT(DATETIME,SUBSTRING(CONVERT(VARCHAR,GETDATE(),103),1,10),103);
DECLARE @ETO VARCHAR(5)='1700';
UPDATE FLIGHT_PLAN_ALLOC SET SDO=@TODAY,EDO=@TODAY,STO=@ETO,ETO=@ETO;
UPDATE FLIGHT_PLAN_SORTING SET SDO=@TODAY,EDO=@TODAY,STO=@ETO,ETO=@ETO;
UPDATE BAG_SORTING SET SDO=@TODAY;

DELETE FROM FLIGHT_PLAN_SORTING WHERE SDO='2014-03-17 00:00:00.000' AND AIRLINE='DL' AND FLIGHT_NUMBER='2133';
--3. INSERT FLIGHT INFO FOR MU7
DECLARE @TODAY DATETIME = CONVERT(DATETIME,SUBSTRING(CONVERT(VARCHAR,GETDATE(),103),1,10),103);
INSERT INTO FLIGHT_PLAN_SORTING VALUES(GETDATE(),NULL,'US','2222',NULL,NULL,@TODAY,'1700',@TODAY,'1700',NULL,NULL,NULL,NULL,NULL,'LAX',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'MU7',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'5',NULL,NULL,NULL,NULL,'BHS',1,1,0);
INSERT INTO FLIGHT_PLAN_SORTING VALUES(GETDATE(),NULL,'AA','3333',NULL,NULL,@TODAY,'1700',@TODAY,'1700',NULL,NULL,NULL,NULL,NULL,'LAX',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'MU7',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'5',NULL,NULL,NULL,NULL,'BHS',1,1,0);




