CREATE PROCEDURE [dbo].[stp_MES_INSERT_BAGINFO]
	@BAG_INFO_TABLETYPE BAG_INFO_TABLETYPE READONLY
AS
BEGIN
	SET NOCOUNT ON;
	DELETE FROM BAG_INFO;
	
    INSERT INTO BAG_INFO (GID, LICENSE_PLATE1, LICENSE_PLATE2, HBS1_RESULT, HBS2_RESULT, HBS3_RESULT, LAST_LOCATION, TIME_STAMP, TYPE) 
	SELECT GID, LICENSE_PLATE1, LICENSE_PLATE2, HBS1_RESULT, HBS2_RESULT, HBS3_RESULT, LAST_LOCATION, TIME_STAMP, TYPE FROM @BAG_INFO_TABLETYPE

END
GO