USE [BHSDB_OKC]
GO
/****** Object:  StoredProcedure [dbo].[stp_MES_INSERT_BAGINFO]    Script Date: 02-04-2014 9:16:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[stp_MES_INSERT_4DIGITSFALLBACKMAPPING]
	@FOUR_DIGITS_FALLBACK_MAPPING_TABLETYPE FOUR_DIGITS_FALLBACK_MAPPING READONLY
AS
BEGIN
	SET NOCOUNT ON;
	DELETE FROM FOUR_DIGITS_FALLBACK_MAPPING;
	
    INSERT INTO FOUR_DIGITS_FALLBACK_MAPPING([ID], [DESTINATION], [DESCRIPTION], [SYS_ACTION],[IS_CHANGED]) 
	SELECT [ID], [DESTINATION], [DESCRIPTION], [SYS_ACTION],0 FROM @FOUR_DIGITS_FALLBACK_MAPPING_TABLETYPE

END
