USE [BHSDB_CLT_LOCAL]
GO
/****** Object:  StoredProcedure [dbo].[stp_MES_INSERT_FUNCTION_ALLOC_GANTT]    Script Date: 02-04-2014 11:39:16 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[stp_MES_INSERT_DESTINATION_PATH_MAPPING]
	@DESTINATION_PATH_MAPPING_TABLETYPE DESTINATION_PATH_MAPPING_TABLETYPE READONLY
AS
BEGIN
	SET NOCOUNT ON;
	DELETE FROM DESTINATION_PATH_MAPPING;
	
    INSERT INTO DESTINATION_PATH_MAPPING([SUBSYSTEM], [PATH]) 
	SELECT[SUBSYSTEM], [PATH] 
    FROM @DESTINATION_PATH_MAPPING_TABLETYPE

END
