USE [BHSDB_OKC]
GO
/****** Object:  StoredProcedure [dbo].[stp_MES_INSERT_FUNCTION_ALLOC_GANTT]    Script Date: 02-04-2014 11:39:16 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[stp_MES_INSERT_SECURITY_GROUP_TASK_MAPPING]
	@SECURITY_GROUP_TASK_MAPPING_TABLETYPE SECURITY_GROUP_TASK_MAPPING_TABLETYPE READONLY
AS
BEGIN
	SET NOCOUNT ON;
	DELETE FROM SECURITY_GROUP_TASK_MAPPING;
	
    INSERT INTO SECURITY_GROUP_TASK_MAPPING([SECU_GROUP_CODE], [SECU_TASK_CODE]) 
	SELECT [SECU_GROUP_CODE], [SECU_TASK_CODE]
    FROM @SECURITY_GROUP_TASK_MAPPING_TABLETYPE

END
