USE [BHSDB_CLT_LOCAL]
GO
/****** Object:  StoredProcedure [dbo].[stp_MES_INSERT_FLIGHT_PLAN_ALLOC]    Script Date: 02-04-2014 11:25:36 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[stp_MES_INSERT_FUNCTION_ALLOC_GANTT]
	@FUNCTION_ALLOC_GANTT_TABLETYPE FUNCTION_ALLOC_GANTT_TABLETYPE READONLY
AS
BEGIN
	SET NOCOUNT ON;
	DELETE FROM FUNCTION_ALLOC_GANTT;
	
    INSERT INTO FUNCTION_ALLOC_GANTT ([ID], [TIME_STAMP], [FUNCTION_TYPE], [RESOURCE], [ALLOC_OPEN_DATETIME], 
			[ALLOC_CLOSE_DATETIME], [IS_CLOSED], [EXCEPTION]) 
	SELECT 	[ID], [TIME_STAMP], [FUNCTION_TYPE], [RESOURCE], [ALLOC_OPEN_DATETIME], 
			[ALLOC_CLOSE_DATETIME], [IS_CLOSED], [EXCEPTION] 
    FROM @FUNCTION_ALLOC_GANTT_TABLETYPE

END
