USE [BHSDB_CLT_LOCAL]
GO
/****** Object:  StoredProcedure [dbo].[stp_MES_INSERT_SECURITY_GROUP_TASK_MAPPING]    Script Date: 02-04-2014 2:33:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[stp_MES_INSERT_SECURITY_TASKS]
	@SECURITY_TASKS_TABLETYPE SECURITY_TASKS_TABLETYPE READONLY
AS
BEGIN
	SET NOCOUNT ON;
	DELETE FROM SECURITY_TASKS;
	
    INSERT INTO SECURITY_TASKS( [SECU_TASK_CODE], [NAME], [SECU_CAT_CODE], [IS_ACTIVE], [DESCRIPTION]) 
	SELECT  [SECU_TASK_CODE], [NAME], [SECU_CAT_CODE], [IS_ACTIVE], [DESCRIPTION]
    FROM @SECURITY_TASKS_TABLETYPE

END
