USE [BHSDB_OKC]
GO
/****** Object:  StoredProcedure [dbo].[stp_MES_INSERT_FUNCTION_ALLOC_GANTT]    Script Date: 02-04-2014 11:39:16 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[stp_MES_INSERT_AIRPORTS]
	@AIRPORTS_TABLETYPE AIRPORTS_TABLETYPE READONLY
AS
BEGIN
	SET NOCOUNT ON;
	DELETE FROM AIRPORTS;
	
    INSERT INTO AIRPORTS([CODE_IATA],[CODE_ICAO],[NAME],[COUNTRY],[CITY]) 
	SELECT [CODE_IATA],[CODE_ICAO],[NAME],[COUNTRY],[CITY] 
    FROM @AIRPORTS_TABLETYPE

END
