USE [BHSDB_OKC]
GO
/****** Object:  StoredProcedure [dbo].[stp_MES_INSERT_SECURITY_GROUP_TASK_MAPPING]    Script Date: 02-04-2014 2:33:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[stp_MES_INSERT_SECURITY_GROUP]
	@SECURITY_GROUP_TABLETYPE SECURITY_GROUP_TABLETYPE READONLY
AS
BEGIN
	SET NOCOUNT ON;
	DELETE FROM SECURITY_GROUPS;
	
    INSERT INTO SECURITY_GROUPS([SECU_GROUP_CODE], [NAME], [SECU_CAT_CODE], [IS_ACTIVE], [DESCRIPTION]) 
	SELECT [SECU_GROUP_CODE], [NAME], [SECU_CAT_CODE], [IS_ACTIVE], [DESCRIPTION] 
    FROM @SECURITY_GROUP_TABLETYPE

END
